techmatters/serverless

- .gitignore
- README.md
- package.json
- utils/generateSignature.js
- utils/params.json
Added little script that will help local development.
Added compile & deploy script.
> Gian signature utility

- functions/setTaskConversationsAttributes.ts
Jira: https://bugs.benetech.org/browse/CHI-133
Frontend: https://github.com/tech-matters/flex-plugins/pull/91
> Function for updating the task conversations attributes

- functions/setTaskConversationsAttributes.ts
- functions/setTaskInsightsData.ts
Jira: https://bugs.benetech.org/browse/CHI-133
Set both `conversations` and `customers` objects of a `task`.
> Save insights data

- functions/transferChatStart.ts
- package-lock.json
- package.json
- tech-matters-serverless-helpers-lib/package.json
- tech-matters-serverless-helpers-lib/src/resolutions.ts
- tests/transferChatStart.test.ts
Added `error403` resolution to the serverless helpers.
> Transfers related code cleanup

- functions/autopilotRedirect.protected.ts
- package-lock.json
- package.json
- tests/autopilotRedirect.test.ts
Put current redirect function into our serverless repo. It will need to be updated as the pre-survey or bot get more complex.
> Added chatbot redirection function and tests.

- functions/adjustChatCapacity.ts
- tests/adjustChatCapacity.test.ts
Jira: https://bugs.benetech.org/browse/CHI-253
This PR is related to https://github.com/tech-matters/flex-plugins/pull/218
This PR is based on the work done in https://github.com/tech-matters/serverless/pull/23
Adds the serverless function needed to perform manual pull worker's chat capacity.
> Clean-up and integration of VPS's code

- .github/workflows/aselo_beta.yml
- .github/workflows/aselo_development.yml
- .github/workflows/south_africa_production.yml
- .github/workflows/south_africa_staging.yml
- .github/workflows/zambia_production.yml
- .github/workflows/zambia_staging.yml
Adding environment variables required for new Serverless releases in GitHub actions.
> Facu actions improve

- functions/listWorkerQueues.ts
This PR is related to https://github.com/tech-matters/flex-plugins/pull/384
This PR adds `listWorkerQueues` function, which given a certain `workerSid`, returns all the queues that matches for such a worker.
Note: some debt is introduced in this PR as no test were written for it.
> Added listWorkerQueues function

- tests/assignOfflineContact.test.ts
This PR un-comment the tests failing (followup of https://github.com/tech-matters/serverless/pull/36) and add more test cases to match current behavior.
> assignOfflineContact.test updated to test new behavior

- functions/assignOfflineContact.ts
This PR added retry logic to `assignOfflineContact`.
> Added retry logic to assignOfflineContact

- functions/assignOfflineContact.ts
- tests/assignOfflineContact.test.ts
This PR is related to https://github.com/techmatters/flex-plugins/pull/442.
This PR adds offline contact routing info into assignOfflineContact function.
> Moved offline contact task routing info to the function

- .github/actions/main-action/action.yml
Reverts techmatters/serverless#65
> Revert "Fixed twilio-cli to version 2.23.0"

- .github/workflows/aselo_development-pre-DRY.yml
Checked out Aselo Dev deploy script prior to DRY version.
> Included old deployment file

- .github/workflows/aselo_development-pre-DRY.yml
Follow up on https://github.com/techmatters/serverless/pull/74.
> Changes on deployment to include custom envvars

- .github/workflows/aselo_development-pre-DRY.yml
Fixed yaml error introduced in https://github.com/techmatters/serverless/pull/76.
> Changes on deployment to include custom envvars (fixed yaml error)

- functions/getWorkerAttributes.ts
Jira: https://bugs.benetech.org/browse/CHI-719
This PR is related to https://github.com/techmatters/flex-plugins/pull/472
Adds a new function that given a worker sid, retrieves it's attributes.
> Added getWorkerAttributes function

- functions/deleteFile.ts
- functions/getFileDownloadUrl.ts
- functions/getFileUploadUrl.ts
- functions/uploadFile.ts
- package-lock.json
- package.json
Jira: https://bugs.benetech.org/browse/CHI-745
primary reviewer: @GPaoloni 
This PR creates 3 functions to handle files on S3:
- getFileUploadUrl
- getFileDownloadUrl
- deleteFile
For these functions to work, those env vars must be set on Twilio:
- ASELO_APP_ACCESS_KEY;
- ASELO_APP_SECRET_KEY;
- S3_BUCKET;
- AWS_REGION;
Also, on AWS, set each bucket CORS policy to:
```
[
{
"AllowedHeaders": [
"*"
],
"AllowedMethods": [
"GET",
"POST",
"PUT"
],
"AllowedOrigins": [
"https://flex.twilio.com/"
],
"ExposeHeaders": []
}
]
```
> Functions to upload, delete and download files to S3

- .github/actions/deploy-beta/action.yml
- .github/actions/healthCheck/action.yml
- .github/actions/healthCheck/dist/licenses.txt
- .github/actions/healthCheck/index.js
- .github/actions/healthCheck/package-lock.json
- .github/actions/healthCheck/package.json
- .github/workflows/aselo_development.yml
- .gitignore
Reopen of https://github.com/techmatters/serverless/pull/97 after a fix in the yml file.
> Split deploy from health check actions

- .github/actions/healthCheck/index.js
Reverts techmatters/serverless#103
> Revert "Intentionally break healthCheck"

- .github/workflows/aselo_beta.yml
- .github/workflows/ethiopia_staging.yml
- .github/workflows/malawi_staging.yml
- .github/workflows/south_africa_staging.yml
- .github/workflows/zambia_staging.yml
This PR updates all the deploy scripts for the staging tier accounts.
Notes: 
- Since here we are including values required for Post Survey and Case Document features, before deploying this we need to check that every resource mentioned in the workflows does exists (or create them if not).
- IMPORTANT! This deployments contain the breaking change from https://github.com/techmatters/serverless/pull/107.
> Update staging deploy workflows

- .github/actions/deploy-beta/action.yml
- .github/workflows/aselo_development.yml
Reverts techmatters/serverless#119
> Revert "Testing slack message"

- .github/actions/deploy-beta/action.yml
- .github/workflows/aselo_development.yml
Reverts techmatters/serverless#121
> Revert "Testing slack message (II)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#123
> Revert "Testing slack message (III)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#125
> Revert "Testing slack message (IV)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#127
> Revert "Testing slack message (V)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#129
> Revert "Testing slack message (VI)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#131
> Revert "Testing slack message (VII)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#133
> Revert "Testing slack message (VIII)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#135
> Revert "Testing slack message (IX)"

- .github/actions/deploy-beta/action.yml
Reverts techmatters/serverless#137
> Revert "Testing slack message (X)"

- .github/actions/custom-actions/action.yml
Reverts techmatters/serverless#160
> Revert "Test workflow with no custom action"

- .github/actions/custom-actions/action.yml
Reverts techmatters/serverless#162
> Revert "Test workflow with no custom action (II)"

- .github/actions/custom-actions/action.yml
Reverts techmatters/serverless#164
> Revert "Test workflow with no custom action (III)"

- .github/workflows/safernet_production.yml
New prod workflow for SaferNet
> Added SaferNet workflow

- .github/workflows/safernet_production.yml
Rename 'SNBR' to 'BR' and 'SaferNet Brazil' to 'SaferNet'
> Rename SaferNet workflow vars

- .github/workflows/aselo_beta.yml
This PR changes the secrets name for Aselo Beta account. Now Beta is considered the Staging environment, hence all of it's variables follows the convention pattern with `STG` env.
> Updated Beta workflow to follow STG convention

- .github/actions/main-action/action.yml
- .github/workflows/aarambh_production.yml
Production release workflow for Aarambh
[ X ] Corresponding issue has been opened
[ N/A ] New tests added
[ N/A ] Strings are localized
Run new workflow.
Verify serverless functions are present & up to date on Aarambh production account
> CHI-837: Aarambh production workflow

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/safernet_staging_custom/action.yml
This adds SaferNet Staging custom action workflow.
SaferNet needs 2 custom ENV VARs. Currently, they were added manually through Twilio Console.
This PR automates deploying them, through a custom action that fetches them SSM and appends them to the .env file used in the main deploy action.
Check that SAFERNET_ENDPOINT and SAFERNET_TOKEN has been deployed
> Add SaferNet Staging custom action

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/safernet_production_custom/action.yml
- .github/workflows/safernet_production.yml
- .github/workflows/safernet_staging.yml
This adds SaferNet Production custom action workflow.
SaferNet needs 2 custom ENV VARs. Currently, they were added manually through Twilio Console.
This PR automates deploying them, through a custom action that fetches them SSM and appends them to the .env file used in the main deploy action.
Check that SAFERNET_ENDPOINT and SAFERNET_TOKEN has been deployed
> SaferNet Production custom action

- .github/workflows/jamaica_staging.yml
Adds workflow file to deploy JM staging.
> Added jm staging workflow

- .github/actions/custom-actions/safernet_production_custom/action.yml
- .github/actions/custom-actions/safernet_staging_custom/action.yml
- functions/savePendingContacts.ts
This PR creates a Serverless Function that tries saving the pending contacts and updates the pending-contacts sync list.
Fixes https://bugs.benetech.org/browse/CHI-880
> Implement Save Pending Contacts from Sync List

- .github/workflows/canada_staging.yml
New deployment workflow for Kids Help Phone (Canada) Staging
- [ X ] Corresponding issue has been opened
- [ N/A ] New tests added
- [ N/A ] Strings are localized
CHI-1016
Run the deploy workflow and test the serverless functions via the flex plugin (once also deployed)
> CHI-1016: New workflow for Kids Help Phone (Canada) Staging

- assets/formDefinitions/ca-v1/postSurvey.private.json
- assets/translations/en-US/postSurveyMessages.private.json
- functions/postSurveyInit.ts
Adds post survey config for the questions that are being tested in CA staging.
> Added post survey config for CA

- .github/workflows/ecpat_philippines_staging.yml
Primary reviewer: @stephenhand 
Deployment file.
Fixes https://bugs.benetech.org/browse/CHI-945
After this is deployed, all functions should be visible on Twilio
> Philippines deployment file

- functions/helpers/customChannels/customChannelToFlex.private.ts
- functions/webhooks/instagram/InstagramToFlex.ts
- functions/webhooks/twitter/TwitterToFlex.ts
This PR implements [this suggestion](https://github.com/techmatters/serverless/pull/190#discussion_r803577940).
> AseloCustomChannels as enum

- functions/webhooks/instagram/InstagramToFlex.ts
- tests/assignOfflineContact.test.ts
- tests/webhooks/FlexChannelUpdate.test.ts
- tests/webhooks/instagram/FlexToInstagram.test.ts
- tests/webhooks/instagram/InstagramToFlex.test.ts
* Test coverage for the new instagram webhhooks
* Fixed some smells in assignOfflineContact test suite
- [ X ] Corresponding issue has been opened
- [ X ] New tests added
- [ N/A ] Strings are localized
Fixes CHI-836
Tested as part of PR checks
>  CHI-836: Instagram webhook tests

- functions/postSurveyInit.ts
Small fix for post-survey wording.
> Change wording for post-survey first message

- .github/actions/custom-actions/aselo_development_custom/action.yml
Removes white spaces at the start of comments to align them in the proper level.
> Removed white spaces in comments

- .github/actions/custom-actions/aselo_development_custom/action.yml
Reverts techmatters/serverless#215
> Revert "Removed white spaces in comments"

- .github/actions/custom-actions/aselo_development_custom/action.yml
- .github/actions/main-action/action.yml
- .github/workflows/aarambh_production.yml
- .github/workflows/aarambh_staging.yml
- .github/workflows/aselo_beta.yml
- .github/workflows/aselo_development.yml
- .github/workflows/canada_staging.yml
- .github/workflows/ecpat_philippines_staging.yml
- .github/workflows/ethiopia_production.yml
- .github/workflows/ethiopia_staging.yml
- .github/workflows/jamaica_production.yml
- .github/workflows/jamaica_staging.yml
- .github/workflows/malawi_production.yml
- .github/workflows/malawi_staging.yml
- .github/workflows/safernet_production.yml
- .github/workflows/safernet_staging.yml
- .github/workflows/south_africa_production.yml
- .github/workflows/south_africa_staging.yml
- .github/workflows/test_staging.yml
- .github/workflows/zambia_production.yml
- .github/workflows/zambia_staging.yml
* Update runtime for all functions to Node 14
* Update all existing workflows to build with Node 14
- [ X ] Corresponding issue has been opened
- [ N/A ] New tests added
- [ N/A ] Strings are localized
CHI-627
Release Aselo Dev serverless
> CHI-627: Update to Node 14

- functions/webhooks/instagram/InstagramToFlex.ts
Primary reviewer: @murilovmachado 
This PR filters out story mention event types coming from Instagram as described in https://bugs.benetech.org/browse/CHI-1077.
- Start a new Instagram based chat.
- As this code is deployed to -dev- enviornment of Aselo Development, you can you mention in a story our development account and that should work not trigger any message in the Flex UI.
> Filter story mentions

- .github/actions/custom-actions/zambia_staging_custom/action.yml
This PR adds CSAM credentials for ZM Staging to be provided from custom action.
> Added CSAM credentials for ZM staging

- .github/actions/custom-actions/zambia_production_custom/action.yml
Set environment flag to live ("L") and country code to ZM contry code (can be found in https://bugs.benetech.org/secure/RapidBoard.jspa?rapidView=19&view=detail&selectedIssue=CHI-1089).
> Added country code and LIVE flag

- .github/workflows/ecpat_philippines_production.yml
Primary reviewer: @stephenhand 
- Adds deploy workflow.
> ECPAT Production: Added deploy workflow

- assets/operatingInfo/uk.private.json
- assets/translations/en-UK/flexUI.private.json
- assets/translations/en-UK/messages.private.json
UK Config
- Add operatingInfo file 
- Add translations file
> Uk stg config042022

- .github/workflows/uk_staging_III.yml
Adds workflow file to deploy UK Staging (III)
NOTE: This workflow is not following the standard naming convention, to avoid collision with the existing uk staging account config.
> Added uk staging (III) workflow

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/malawi_production_custom/action.yml
- .github/actions/custom-actions/malawi_staging_custom/action.yml
Primary Reviewer: @GPaoloni 
* Configures Malawi Production for live IWF reporting and Malawi Staging for test IWF reporting
Send test IWF report on Malawi Staging once the feature flag has been set
> Add IWF reporting related custom actions for Malawi staging & prod

- .github/workflows/te_guio_colombia_staging.yml
Primary reviewer: @stephenhand @GPaoloni 
- New feature: Setting up Te Guio Colombia Staging
- [N/A] Corresponding issue has been opened
- [N/A] Strings are localized
Fixes # N/A
This is a draft PR to me help me figure out why `terraform apply` keeps failing.
> CHI-1188: Set up Te Guio Colombia Staging

- .github/workflows/te_guio_colombia_staging.yml
> CHI-1188: update Te Guio Colombia Staging yml file

- .github/actions/custom-actions/aarambh_staging_custom/action.yml
- .github/actions/custom-actions/action.yml
Added required env vars to IN staging for IWF reporting.
NOTE: this does not includes country code nor environment as we only want for testing mode prior to enabling in production account.
> Added IWF vars to IN stg

- .github/workflows/teguio_colombia_staging.yml
- New Feature: Set up for Te Guio Colombia II helpline
- 
Fixes #252 
CHI-1188
> CHI-1188: set up te guio colombia II helpline

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/teguio_staging_custom/action.yml
Modifying the "main" action to include the TeGuio Staging Custom action and adding the custom action  teguio_staging for the twitter setup.
> Adding twitter custom action for CO STG

- .github/actions/custom-actions/aarambh_production_custom/action.yml
- .github/actions/custom-actions/action.yml
Added required env vars to IN prod for IWF reporting.
NOTE: as `IWF_API_ENVIRONMENT` variable is commented out in the action, test mode will be deployed. Once we want this to go live we must create `PROD_IN_IWF_API_ENVIRONMENT` Parameter Store (AWS) variable with the `L` value and un-comment the corresponding code in `.github/actions/custom-actions/aarambh_production_custom/action.yml`
> Added IWF vars to IN prod (test mode)

- .github/actions/custom-actions/aarambh_production_custom/action.yml
- .github/actions/custom-actions/malawi_production_custom/action.yml
- .github/actions/custom-actions/zambia_production_custom/action.yml
- functions/reportToIWF.ts
- tests/reportToIWF.test.ts
Includes changes for #255 - perhaps wait for this to be merged to review
Primary Reviewer @GPaoloni 
Allows custom channel IDs to be set in payloads we report to IWF, as they requested
Fixes CHI-1309
?
> CHI-1309: Custom channel ids

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/aselo_beta_custom/action.yml
- .github/actions/custom-actions/jamaica_staging_custom/action.yml
Added required env vars via custom actions so Jamaica Staging and Aselo Beta can use Instagram integration.
> Gian jm beta instagram

- .github/actions/custom-actions/aselo_development_custom/action.yml
Adjusted name of Aselo Development PAT variable after changes requested by @dee-luo.
> Adjusted facebook pat name

- .github/workflows/zimbabwe_staging.yml
- New feature: Childline  Zimbabwe setup
Fixes CHI-1316
> CHI-1316: add childline  Zimbabwe yml workflow file

- .github/workflows/flex2_staging.yml
Yml file for `Flex 2.0 Staging`
> Flex 2.0 Staging Yml file

- assets/translations/es/postSurveyMessages.private.json
This PR just adds the file spanish language file postSurveyMessages.private.json
> adding spanish translation file

- .github/workflows/romania_staging.yml
> Change AWS region in workflow for Romania Staging

- .github/actions/custom-actions/aselo_development_custom/action.yml
- functions/helpers/customChannels/customChannelToFlex.private.ts
- functions/webhooks/line/FlexToLine.protected.ts
- functions/webhooks/line/LineToFlex.ts
- package-lock.json
- package.json
- tests/webhooks/line/FlexToLine.test.ts
- tests/webhooks/line/LineToFlex.test.ts
This PR:
- Implement webhook to **receive** messages from Line
- Implement webhook to **send** messages to Line
- Adds **env vars** related to Line integration
- Updates `@twilio/runtime-handler` so that it accepts request headers
To do:
- ~Unit tests~ (done)
What this PR does **NOT** do:
- Checks the children username on Line. It displays `child`, for now.
Fixes:
- https://bugs.benetech.org/browse/CHI-1328
- https://bugs.benetech.org/browse/CHI-1329
> Webhooks for receiving and sending messages from line

- .github/actions/custom-actions/teguio_staging_custom/action.yml
Adding Instagram variables for CO custom action
@GPaoloni  what do you think?
> Adding instagram to custom action for CO

- assets/formDefinitions/co-v1/insights/postSurvey.private.json
Adding Post Survey - Insights mapping for Te Guio CO
> Adding post survey to Te Guío CO

- assets/translations/es-CO/flexUI.private.json
- assets/translations/es-CO/messages.private.json
- assets/translations/es-CO/postSurveyMessages.private.json
Adding post survey Spanish translations for Te Guío CO.
FYI @Humairaa127  @GPaoloni
> Adding post survey Spanish translations for Te Guío CO.

- .github/actions/custom-actions/safernet_staging_custom/action.yml
Adding env variables to custom actions for SaferNet BR staging.
FYI @Humairaa127 @GPaoloni
> Adding Instagram Env Variables for SaferNet BR Staging

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/jamaica_production_custom/action.yml
Adds custom action for the SafeSpot (JM) Production environment. This action will attach the corresponding PS variables to integrate Instagram messaging.
> Added custom actions for jm production

- .github/actions/custom-actions/aselo_development_custom/action.yml
- .github/actions/custom-actions/safernet_staging_custom/action.yml
Just Update Line variables' name on deployment files.
> Update Line Env Vars on Deployment Files

- package-lock.json
- package.json
> adding @twilio/runtime-handler 1.2.4

- assets/operatingInfo/co.private.json
Minor update changing webchat to web
> webchat -> web

- .github/actions/custom-actions/thailand_staging_custom/action.yml
Adding Twitter and Instagram env variables to TH Staging
> Adding Twitter and Instagram to TH

- .github/actions/custom-actions/thailand_staging_custom/action.yml
> SIDD -> SID

- .github/workflows/telefonzaufania_pl_staging.yml
@GPaoloni @acedeywin 
Adding Telefon Zaufania (PL) Staging workflow
@acedeywin  TODO:  can you add this to the parallel deployment?
> adding pl staging workflow

- .github/workflows/deploy-helplines-parallel-worflows.yml
- .github/workflows/hungary_staging.yml
> CHI-1425: Rework UKR deploy workflow to deploy to HU

- package-lock.json
- package.json
- tech-matters-serverless-helpers-lib/package.json
- tech-matters-serverless-helpers-lib/src/taskrouter/eventTypes.ts
> Fix event types

- .github/workflows/deploy-helplines-parallel-worflows.yml
Reverts techmatters/serverless#346
> Revert "add @branch reference"

- .github/actions/main-action/action.yml
- .github/workflows/deploy-helplines-parallel-worflows.yml
- Bug fix: Fix helpline identifier in slack meassge
Fixes chi-1259
> Chi 1259 workflow to deploy serverless helpline stg norerun

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/teguio_production_custom/action.yml
Primary reviewer
@GPaoloni  or @stephenhand 
Adding Twitter and Instagram channels to Te Guío CO production release.
- [na] New tests added
Fixes #....
> adding custom actions for Te Guio Production: Twitter and Instagram

- .github/actions/custom-actions/action.yml
FYI @stephenhand 
Reviews just for visbility
Fixes #....
> adding missing quote

- assets/operatingInfo/co.private.json
FYI @GPaoloni  @mmythily 
Updating web to website. This is needed for the operating info hours logic to work.
For CO production this requires to be deployed at the same time where CO terraform changes are applied.
Deployment steps:
I'm putting this to keep a record of what needs to be done.
terraform state rm    'module.twilioChannel["web"].twilio_studio_flows_v2.channel_messaging_flow'
terraform state rm  'module.twilioChannel["web"].twilio_flex_flex_flows_v1.channel_flow'
terraform import -var-file <file>.private.tfvars  'module.twilioChannel["webchat"].twilio_flex_flex_flows_v1.channel_flow'  FOf1ace264485595c61b9d926657c105c0
terraform import -var-file <file>.private.tfvars 'module.twilioChannel["webchat"].twilio_studio_flows_v2.channel_messaging_flow' …
> Updating web to webchat

- .github/workflows/kellimni_production.yml
primary reviewer: @GPaoloni 
Adds github workflow malta production
CHI-1538
> chore: add malta prod github actions workflow

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/kellimni_production_custom/action.yml
@stephenhand or @GPaoloni  Does this look OK? , this needs to go on Prod this week. 
Adding custom actions for MT PROD
FYI I'm well aware that we are not matching the STG environment because we are only connecting IG to the PROD setup, this is not ideal, but since this deployment has to go ASAP we've decided to skip some steps in the staging deployment in favour of time.
Fixes #....
> adding custom flow for MT prod

- functions/endChat.ts
Primary Reviewer: @GPaoloni 
Slight tweak to channel cleanup logic in endChat function
Fixes #CHI-1610
Ensure end chat exits correctly when clicked waiting for a counsellor
> CHI-1610: Ensure we always try to clean up channel if endChat results in task cancellation

- assets/operatingInfo/br.private.json
- assets/operatingInfo/ph.private.json
- assets/operatingInfo/za.private.json
Reviews just for visibility
Fixes #....
> holiday updates

- .github/workflows/aselo_production.yml
- .github/workflows/cl_linealibre_production.yml
- .github/workflows/thailand_production.yml
- .github/workflows/zimbabwe_production.yml
Serverless production workflow. Since this is part of a prod account setup I do think I need an approval.
Fixes #....
> Production workflows

- .github/actions/custom-actions/aarambh_production_custom/action.yml
- .github/actions/custom-actions/aarambh_staging_custom/action.yml
- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/aselo_development_custom/action.yml
- .github/actions/main-action/action.yml
- .github/workflows/aarambh_production.yml
- functions/selfReportToIWF.ts
- tests/selfReportToIWF.test.ts
* Self signed certs are only allowed when a flag is set
* Renamed SSM parameters to match new convention
* Aselo Development flagged to allow self signed certs
* Rati Prod & Staging configured for self reported CSAM (staging allows self signed HTTPS)
TODO: Update SSM parameters
CHI-1484
* Deploy to Rati Staging & Aselo Development & regression test self reported CSAM
Deploy to prod cannot be tested
> CHI-1484: Self signed certs flag

- .github/workflows/custom_helpline.yml
- .github/workflows/serverless-pre-release-qa.yml
Fix QA release & refactor it to call custom_helpline.yml rather than the E2Ev specific workflow
> QA release call custom_helpline to deploy E2E

- .github/workflows/serverless-pre-release-qa.yml
Reverts techmatters/serverless#403
> Revert "Pinned e2e deploy to branch"

- functions/taskrouterListeners/transfersListener.private.ts
- tests/taskrouterListeners/transfersListener.test.ts
This PR is related to https://github.com/techmatters/flex-plugins/pull/1307
While working on the linked PR, after fixing the bug, I've noticed that rejecting a warm voice transfer after joining the conference will also close the original task, causing an ugly bug where the original counselor does not have a way to interact with the call, but the communication was still open with the caller.
This PR adds a check to the warm transfers case in charge of closing the tasks in wrapup state, to only do so if the transfer is `accepted` (either a `COLD` transfer or a fully accepted `WARM` transfer will be in this state).
The rejected `WARM` transfer does enters this case, as the `transferStatus` is `rejected`, and the rejecting side will close the rejected task from the frontend.
- Make sure that …
> Added condition to only close original task if transfer is accepted

- assets/translations/es-CL/messages.private.json
- assets/translations/es-CL/postSurveyMessages.private.json
adding post survey messages
Fixes #....
> adding post survey messages

- assets/operatingInfo/th.private.json
removing holidays from TH. Reviewers for visibility.
Fixes #....
> Removing holidays

- assets/operatingInfo/th.private.json
removing holidays from TH 
reviewers for visibility
Fixes #....
> Removing holidays (#429)

- assets/operatingInfo/cl.private.json
- assets/translations/es-CL/messages.private.json
@GPaoloni  Operating hours should also work for voice right?
Fixes #....
> operating hours for CL

- assets/operatingInfo/cl.private.json
deleted some extra brackets
Fixes #....
> Fixing json file format

- assets/operatingInfo/cl.private.json
- assets/operatingInfo/th.private.json
- assets/translations/es-CL/messages.private.json
cherry picking changes from master
Fixes #....
> Alejandro cl cherry picking fixes

- assets/translations/es/messages.private.json
-Adding more spanish translations
> WA Demo changes

- .github/workflows/canada_production.yml
Adding CA production workflow
@stephenhand or @GPaoloni if any of you can approve this that would be great!
Fixes #....
> CA PROD workflow

- .github/workflows/deploy-all-staging-accounts.yml
- .github/workflows/youthline_nz_staging.yml
Reviewers for visibility. Adding NZ staging workflows
Fixes #....
> Adding NZ workflow

- assets/operatingInfo/nz.private.json
- assets/translations/en-NZ/flexUI.private.json
- assets/translations/en-NZ/messages.private.json
- assets/translations/en-NZ/postSurveyMessages.private.json
Adding operating hours for NZ
Fixes #....
> nz operating hours

- .github/workflows/serverless-pre-release-qa.yml
Adds the parameters used in the QA release workflow to line up with the ones used by custom_helpline.
- [N/A] Corresponding issue has been opened
Fixes N/A
> bug: add missing inputs for release workflow

- assets/formDefinitions/cl-v1/insights/postSurvey.private.json
> insights mapping cl

- functions/endChat.ts
- functions/getMessages.ts
- functions/getTranslation.ts
- functions/operatingHours.ts
- functions/postSurveyComplete.protected.ts
- functions/postSurveyInit.ts
- tests/getMessages.test.ts
- tests/getTranslation.test.ts
- tests/operatingHours.test.ts
Public assets cannot be fetched with `Runtime.getAssets()`.
This PR implements fetching the translation files (public) with `axios`.
> Load public assets with axios

- functions/getExternalRecordingS3Location.ts
- tests/getExternalRecordingS3Location.test.ts
> CHI-2118: function to retrieve s3 storage info for external recordings

- assets/translations/en-NZ/messages.json
Changing message for NZ
Fixes #....
> nz new message

- functions/postSurveyComplete.protected.ts
- functions/postSurveyInit.ts
Removed unnecessary console.error statements when fail to retrieve translation.
> Removed unnecessary console.error statements

- assets/operatingInfo/nz.private.json
Update nz.private.json operating hours
Reviewers for visibility 
Fixes #....
> Update nz.private.json operating hours

- .github/workflows/deploy-all-production-accounts.yml
> Fix production workflow file

- .github/actions/custom-actions/teguio_production_custom/action.yml
- .github/actions/custom-actions/teguio_staging_custom/action.yml
Removing Twitter from CO actions STG and PROD
Fixes #....
> removing twitter params

- functions/sendStudioMessage.protected.ts
This PR fixes an issue where `sendStudioMessage` was triggering another Studio execution.
This is fixed by removing the webhook of type `studio` before sending a message.
Fixes https://tech-matters.atlassian.net/browse/CHI-2170
Alejandro already checked that this is not happening anymore with this code.
If you want to double-check, you can use Instagram to contact Aselo Development.
> Prevent sendStudioMessage to trigger another studio execution

- package-lock.json
> Dependency audit fix - fixes critical security issues

- .github/workflows/check-license-header.yml
- .github/workflows/deploy-all-production-accounts.yml
- .github/workflows/deploy-all-staging-accounts.yml
- .github/workflows/deploy-multiple-accounts.yml
- .github/workflows/serverless-ci.yml
- .github/workflows/serverless-pre-release-qa.yml
- .github/workflows/serverless-production-release.yml
This bumps checkout action form v2 to v3 so that it is using a version of node that isn't unsupported.
> chore: bump checkout action version

- .github/actions/custom-actions/aselo_beta_custom/action.yml
- .github/actions/custom-actions/aselo_development_custom/action.yml
- .github/actions/custom-actions/thailand_staging_custom/action.yml
- .github/actions/custom-actions/zambia_production_custom/action.yml
- .github/actions/custom-actions/zambia_staging_custom/action.yml
Removing all twitter keys from actions since this channel is not longer supported.
Fixes #....
> Removing twitter keys from actions

- .github/workflows/deploy-multiple-accounts.yml
Refactor how to set helpline code
- Since we can't provision a lex chatbot with e2e as the helpline code we will have to change the helpline code for the E2E account to "ee" on serverless
Fixes [CHI-2213](https://tech-matters.atlassian.net/browse/CHI-2213)
Deploy to all helpline and make sure they were all successful
[CHI-2213]: https://tech-matters.atlassian.net/browse/CHI-2213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Chi 2213 migrate e2e account autopilot lex

- assets/translations/en-ZA/flexUI.json
- assets/translations/en-ZA/messages.json
- assets/translations/en-ZA/postSurveyMessages.json
@Humairaa127  do these messages look correct? 
Fixes #....
> za messages

- .github/workflows/deploy-multiple-accounts.yml
> Node18 deploy runner

- .github/workflows/deploy-multiple-accounts.yml
Cherry-pick Steve's fix  
Fixes #....
> Bump deploy workflow to use node 18

- .github/workflows/deploy-multiple-accounts.yml
Workflow Changes: This PR is for the first task of [this ticket](https://tech-matters.atlassian.net/browse/CHI-2388) which is to migrate all Github actions to pull the appropriate secrets out of SSM.
Fixes [CHI-2388](https://tech-matters.atlassian.net/browse/CHI-2388)
[CHI-2388]: https://tech-matters.atlassian.net/browse/CHI-2388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improve github provider credential management in twilio-iac and infrastructure-config

- package-lock.json
- package.json
Reverts techmatters/serverless#538
> Revert "Bump axios from 0.26.1 to 1.6.0"

- assets/operatingInfo/br.private.json
> BR: holidays update

- assets/operatingInfo/br.private.json
> BR: updating holidays

- .github/actions/main-action/healthcheck.ts
- .github/actions/main-action/package.json
- .github/workflows/deploy-all-production-accounts.yml
Reverts techmatters/serverless#551
> Revert "JS action code"

- .github/actions/main-action/healthcheck.js
- .github/actions/main-action/package.json
- .github/workflows/deploy-all-production-accounts.yml
Reverts techmatters/serverless#552
> Revert "Revert "JS action code""

- .github/actions/custom-actions/aselo_development_custom/action.yml
This PR sets up Aselo Development to deploy Modica environment variables
Fixes #https://tech-matters.atlassian.net/browse/CHI-2393
Deploy and check the env vars got deployed
> Modica custom actions for AS DEV

- .github/actions/main-action/action.yml
- tsconfig.json
> CHI-2389: Set serverless runner to node 18

- functions/channelCapture/chatbotCallbackCleanup.protected.ts
This PR adds safe-guards to `chatbotCallbackCleanup` function, in case that `capturedChannelAttributes` is not present in channel attributes. This is in order to allow the cleanup to succeed even in those cases where the capture function fails before even attempting to create this property.
- Deploy this code to Development.
- Update Messaging Studio Flow, passing an invalid parameter to the "capture channel with bot" widget.
- Start a new web contact.
- Confirm that even when the capture fails, the chat is not blocked (the capture is "cleaned-up").
> fix: safeguards chatbotCallbackCleanup

- functions/webhooks/instagram/FlexToInstagram.protected.ts
- tests/webhooks/instagram/FlexToInstagram.test.ts
- same as this [PR](https://github.com/techmatters/serverless/pull/574) but for patch release
> Upgrade Graph API to v19 for supporting instagram messages (for patch release)

- assets/translations/en-NZ/messages.json
reviewers for visibility
Fixes #....
> NZ: Updating automated messages 

- functions/selfReportToIWF.ts
- package-lock.json
- package.json
> dependabot/npm and yarn/axios 0.28.0 Fixes

- assets/translations/en-NZ/messages.json
> NZ: automatic messages

- assets/operatingInfo/sg.private.json
- assets/translations/en-SG/messages.json
Adding helpline operating hours for Tinkle Friend webchat (voice will be added a later stage)
> SG Operating hours

- assets/translations/en-NZ/messages.json
Reviewers for visibility 
Fixes #....
> NZ: Updating message

- assets/translations/en-NZ/messages.json
> NZ: Alejandro/nz/cherry pick 070424

- .github/pull_request_template.md
Long overdue specific PR template for HRM - copied from proposed Flex update https://github.com/techmatters/flex-plugins/pull/2138
> PR template specifically for repo

- assets/translations/en-SG/messages.json
> SG - Translation Message

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/youthline_staging_custom/action.yml
This PR creates the custom action for NZ Staging (Youthline) that deploys the environment variables for Modica Integration to work.
Check Environment Variables are deployed on Twilio Functions
> Setup Modica on NZ Staging

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/youthline_production_custom/action.yml
Adding custom action for NZ prod
None
> NZ: adding custom action

- .github/actions/custom-actions/aselo_beta_custom/action.yml
- Removed deprecated workflow for instagram
None
> Fix as staging issue

- functions/getProfileFlagsForIdentifier.protected.ts
This PR is a fix to a reported bug, where profiles are not being properly blocked when the channel is voice. This is due to a misalignment, since we forgot to "trim spaces" in this repo after the fixes done a while back around Twilio using spaced-numbers for some channels. The fix is to replicate the changes from https://github.com/techmatters/flex-plugins/pull/2247 into `getProfileFlagsForIdentifier` function, for it to grab the appropriate identifiers.
3. Only then move the ticket into the QA column in …
> fix: getProfileFlagsForIdentifier - trim spaces in identifiers [CHI-2750]

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/youthline_production_custom/action.yml
Cherry picking NZ PROD custom action
None
> NZ: Alejandro/nz/cherry picks

- functions/getProfileFlagsForIdentifier.protected.ts
> CHI-2758 fix axios calls

- .github/actions/custom-actions/aselo_development_custom/action.yml
- functions/helpers/customChannels/customChannelToFlex.private.ts
- functions/helpers/customChannels/flexToCustomChannel.private.ts
- functions/webhooks/line/FlexToLine.protected.ts
- functions/webhooks/line/LineToFlex.ts
- functions/webhooks/telegram/FlexToTelegram.protected.ts
- functions/webhooks/telegram/TelegramToFlex.ts
Working POC of the serverless implementation for a Telegram custom channel over conversations:
TODO:
Unit Tests
Fix post surveys (wider conversations issue)
Any custom media support required
QA
None
> CHI-2639: Telegram Custom Channel (POC)

- functions/taskrouterListeners/transfersListener.private.ts
- functions/transfer/helpers.private.ts
- functions/transferChatStart.ts
This PR merges the fix introduced in https://github.com/techmatters/serverless/pull/622 against the latest rc branch.
> chore: bug fix - duplicate contact created when transfer rejected on a queue [CHI-2803]

- functions/channelCapture/captureChannelWithBot.protected.ts
- functions/channelCapture/channelCaptureHandlers.private.ts
- functions/helpers/chatChannelJanitor.private.ts
- functions/interaction/transitionAgentParticipants.ts
- functions/postSurveyInit.ts
- functions/taskrouterListeners/janitorListener.private.ts
- functions/taskrouterListeners/postSurveyListener.private.ts
- package-lock.json
- package.json
- tests/interaction/transitionAgentParticipants.test.ts
This PR fixes post surveys for conversations.
It requires a different way of wrapping up a task using the interactions API. This is encapsulated in a new function defined in this PR.
It also requires some updates to flex which are defined in this PR: https://github.com/techmatters/flex-plugins/pull/2343 (programmable chat and conversations minus post surveys should work without that version of flex)
Test WIP 
None
Test post surveys on conversations channels
3. Only then move the ticket into the QA column in …
> CHI-2770: Adjust post survey to fix conversations tasks

- functions/helpers/customChannels/customChannelToFlex.private.ts
- functions/helpers/customChannels/flexToCustomChannel.private.ts
- functions/webhooks/telegram/FlexToTelegram.protected.ts
- functions/webhooks/telegram/TelegramToFlex.ts
- tests/helpers.ts
- tests/interaction/transitionAgentParticipants.test.ts
- tests/webhooks/telegram/FlexToTelegram.test.ts
- tests/webhooks/telegram/TelegramToFlex.test.ts
Unit test coverage and minor tweaks to telegram custom channel.
Tests also cover the generic functions used by custom channels on conversations for the first time
- N/A Feature flags / configuration added
None
Build is green
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion is …
> CHI-2777: unit tests

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/aselo_staging_custom/action.yml
Adding Aselo Staging custom action for Telegram integration
FYI @stephenhand 
None
> AS: Adding Aselo Staging custom action for Telegram integration

- .github/actions/custom-actions/action.yml
> AS: Passing account-sid

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/aselo_development_custom/action.yml
- .github/actions/custom-actions/jamaica_staging_custom/action.yml
- functions/channelCapture/captureChannelWithBot.protected.ts
- functions/helpers/customChannels/customChannelToFlex.private.ts
- functions/helpers/customChannels/flexToCustomChannel.private.ts
- functions/webhooks/instagram/FlexToInstagram.protected.ts
- functions/webhooks/instagram/InstagramToFlex.ts
- tests/interaction/transitionAgentParticipants.test.ts
- tests/webhooks/instagram/FlexToInstagram.test.ts
- tests/webhooks/instagram/InstagramToFlex.test.ts
- tests/webhooks/telegram/FlexToTelegram.test.ts
- tests/webhooks/telegram/TelegramToFlex.test.ts
Instagram now configurable to work on conversations
None
Ensure /development/instagram/ACd8a2e89748318adf6ddff7df6948deaf/messaging_mode is set to 'conversations' and deploy serverless containing this PR to Aselo Development
Test instagram
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the …
> CHI-2784: Instagram on conversations

- .github/actions/custom-actions/aselo_development_custom/action.yml
- functions/webhooks/modica/FlexToModica.protected.ts
- functions/webhooks/modica/ModicaToFlex.ts
- tests/webhooks/modica/FlexToModica.test.ts
- tests/webhooks/modica/ModicaToFlex.test.ts
This PR implements Conversations for Modica.
It also implements an easy switch between Programmable Chat and Conversations.
https://tech-matters.atlassian.net/browse/CHI-2785
Send a message through Modica and check that it works just fine.
Currently AS DEV is set to use conversations.
The tricky thing would be to use Modica, so my advice is to check this when QAing.
You are responsible for ensuring the above steps are completed. If you move a ticket …
> Modica on Conversations

- functions/channelCapture/captureChannelWithBot.protected.ts
Trivial change, merging without approval
> CHI-2770: Fix isConversation check in captureChannelWithBot

- functions/pullTask.ts
- functions/taskrouterListeners/adjustCapacityListener.private.ts
Cherry pick iof same fix on master
None
> CHI-2818: RC cherry pick

- assets/translations/en-CA/messages.json
> CA: Update messages.json

- .github/actions/custom-actions/action.yml
> fix: Add custom action for Childline Thailand Staging release

- tests/webhooks/serviceConversationListener.test.ts
- This is the unit test to the [Alert service user for unsupported media](https://github.com/techmatters/serverless/pull/649) ticket
None
> CHI-2790: Alert service user for unsupported media test

- functions/getProfileFlagsForIdentifier.protected.ts
- tsconfig.json
Replicate the changes of https://github.com/techmatters/flex-plugins/pull/2461 in this repo. For more details, refer to the Flex PR.
> chore: remove hyphens from phone numbers [CHI-2873]

- .github/actions/main-action/action.yml
- .github/workflows/deploy-multiple-accounts.yml
- This PR uses custom action in [flex](https://github.com/techmatters/flex-plugins/pull/2464) to update all deploys 
None
> CHI-2829: Deployment matrix - use custom action in flex to update Google sheet

- assets/translations/en-JM/flexUI.json
- assets/translations/en-JM/messages.json
- assets/translations/en-JM/postSurveyMessages.json
> JM: adding en JM language

- .github/actions/custom-actions/action.yml
> chore:pass input of account sid for routing custom action

- .github/actions/custom-actions/aselo_production_custom/action.yml
Updating custom-actions file for conversations migration
> AS Production Conversations

- .github/actions/custom-actions/aselo_production_custom/action.yml
Cherry picking Line variable updates for conversation migration
Setting up Instagram variables
> AS Production Conversation Migrations

- .github/workflows/serverless-ci.yml
- .github/workflows/serverless-pre-release-qa.yml
> Move last 2 node 16 build runners to node 18

- .github/actions/custom-actions/thailand_staging_custom/action.yml
Updating Line staging environment variables in Childline TH custom actions file for the conversations migration
> Conversations Migration - Line

- functions/getProfileFlagsForIdentifier.protected.ts
This pull request introduces support for ConversationTrigger in the event handling for channels with the new Conversations API. This fixes the bug in the Conversations-based WhatsApp channel which was not able to successfully call getProfileFlagsForIdentifier. 
- In addition, this PR also introduced a channelType property to Studio flows in the getProfileFlagsForIdentifier widget with the channelType property. The complete body now looks like this: 
`{"trigger": {{trigger | to_json}}, "channelType": "whatsapp"}`. This needs to be addressed studio-flow configuration in twilio-iac to be updated to specify the channelType
None
2. Comment on the ticket …
> Add ConversationTrigger for channels using Conversations

- .github/actions/custom-actions/jamaica_staging_custom/action.yml
- .github/actions/custom-actions/teguio_staging_custom/action.yml
- .github/actions/custom-actions/thailand_staging_custom/action.yml
Updating the Custom Actions files and migrating Instagram Channel in Staging to Conversations
> Conversations Migration - Instagram Staging

- .github/actions/custom-actions/teguio_staging_custom/action.yml
CO. custom actions file was missing the below:
```
inputs:
account-sid:
description: 'The Twilio Account SID for this account'
required: true
```
> CO Custom actions fix

- .github/actions/custom-actions/action.yml
Adding the parameter for accountSID for CO staging
> CO Deploy Issue fix

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/aselo_production_custom/action.yml
- .github/actions/custom-actions/jamaica_staging_custom/action.yml
- .github/actions/custom-actions/teguio_staging_custom/action.yml
- .github/actions/custom-actions/thailand_staging_custom/action.yml
Cheery picking all changes made to custom actions files for conversations migrations, from RC branch to Master
> CM - Cherrypick custom actions updates

- .github/actions/main-action/action.yml
- .github/workflows/deploy-all-production-accounts.yml
- .github/workflows/deploy-all-staging-accounts.yml
- .github/workflows/deploy-multiple-accounts.yml
- functions/channelCapture/channelCaptureHandlers.private.ts
Add separate regions for passing into serverless env vars and looking up the google sheets creds via SSM.
Minor logging and naming tidy ups
- [N/A] Feature flags / configuration added
None
Deploy an EU helpline and test the chatbot
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does …
> CHI-2926: Fix regions in deployments

- assets/translations/en-NZ/messages.json
> NZ: message update

- .github/actions/custom-actions/action.yml
- functions/getProfileFlagsForIdentifier.protected.ts
- tsconfig.json
> V1.19 rc merge

- assets/translations/en-SG/messages.json
Tinkle Friend (SG) updates
- Update call and chat busy messages
> SG closing message

- functions/taskrouterListeners/createContactListener.private.ts
- functions/taskrouterListeners/janitorListener.private.ts
- functions/transfer/helpers.private.ts
- tests/taskrouterListeners/janitorListener.test.ts
- Fix channel janitor to use customChannelType as well as channelType to determine if the task is for a custom channel
- Fixed checks for channel janitor so task control checks look at reservation sid, not task sid
None
See ticket
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following …
> CHI-2878: Channel Janitor Fixes for Queue Transfers

- functions/taskrouterListeners/createContactListener.private.ts
- functions/taskrouterListeners/janitorListener.private.ts
- functions/transfer/helpers.private.ts
- tests/taskrouterListeners/janitorListener.test.ts
> Chi 2878 fix custom channel deactivate

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/jamaica_production_custom/action.yml
- .github/actions/custom-actions/teguio_production_custom/action.yml
- .github/actions/custom-actions/thailand_production_custom/action.yml
Update custom action files for Conversations Migration on production accounts
Helplines: CO, TH, JM
> Conversation Migration - Production

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/jamaica_production_custom/action.yml
- .github/actions/custom-actions/teguio_production_custom/action.yml
- .github/actions/custom-actions/thailand_production_custom/action.yml
> PATCH: Alejandro/v1.20 rc cherry picks

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/kellimni_staging_custom/action.yml
Add Telegram variables to MT staging custon actions
None
> MT Staging Telegram variables

- .github/actions/custom-actions/aselo_staging_custom/action.yml
Adding IG params for AS STG
None
> AS STG : Adding IG params

- .github/actions/custom-actions/kellimni_staging_custom/action.yml
Add 'input' on Kellimni staging customs action file. 
None
> MT Custom Action fix

- .github/actions/custom-actions/kellimni_staging_custom/action.yml
> MT Custom Actions Format

- .github/actions/custom-actions/kellimni_staging_custom/action.yml
> MT yaml file format

- functions/transferChatStart.ts
> Fix issue seen in regression with some direct transfers

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/kellimni_production_custom/action.yml
Migrating MT Instagram in Production to conversations
None
> Conversation Migration: MT Instagram

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/kellimni_production_custom/action.yml
> Conversations MT Instagram

- .github/actions/custom-actions/action.yml
- .github/actions/custom-actions/kellimni_production_custom/action.yml
- .github/actions/custom-actions/youthline_production_custom/action.yml
> V1.21 rc merge

- functions/getTask.ts
Also fix completeTaskAssignment to throw 403 rather than 400 for non supervisors
None
Depl;oy and test as part of ticket
> CHI-3099: Add getTask endpoint to support fixed 'Save and End' task functionality

- .github/actions/custom-actions/youthline_production_custom/action.yml
@GPaoloni  I'm going to add this to the RC branch so we can deploy it :) 
None
> NZ PROD: custom action nz

- .github/workflows/deploy-multiple-accounts.yml
Second iteration of https://github.com/techmatters/serverless/pull/732.
None
> fix: slack action v2.0.0 broken message

- assets/translations/en-USCR/flexUI.json
- assets/translations/en-USCR/messages.json
- assets/translations/en-USCR/postSurveyMessages.json
This is just temporary
@michelegomich  FYI 
None
> uscr translations

- .github/actions/custom-actions/youthline_production_custom/action.yml
> v1.24-rc merge to master

- .github/workflows/serverless-pre-release-qa.yml
> Fix playwright dependencies

- functions/getTask.ts
- functions/getTaskAndReservations.ts
> CHI-3190 get task to v1.26-rc

- assets/operatingInfo/nz.private.json
> NZ: emergency webchat operating hours update

- assets/translations/en-NZ/messages.json
> NZ: message updates

- assets/operatingInfo/nz.private.json
> NZ: emergency update (#759)

- .github/workflows/serverless-pre-release-qa.yml
> Release build with node 20

- .github/actions/custom-actions/csema_production_custom/action.yml
> add prod variables

- .github/workflows/serverless-pre-release-qa.yml
> V1.35 rc master merge

- .github/actions/custom-actions/action.yml
> Add TZ var

- .github/actions/custom-actions/action.yml
> add vars to rc

- .github/actions/custom-actions/action.yml
> TZ Custom Action Fix

- assets/translations/en-USCH/postSurveyMessages.json
> USCH: post survey messages

- .github/actions/custom-actions/aselo_production_custom/action.yml
> AS Prod - Modica Setup
