functions/populateCounselors.ts

Jira : https://bugs.benetech.org/browse/CHI-111
- No-helpline counselors are added to the result when filtering for helpline (excluding only those with a helpline that is not empty nor equal to the given)

No-helpline counselors are added when filtering for helpline

---

functions/transferChatResolve.ts
functions/transferChatStart.ts
tests/helpers.ts
tests/transferChatResolve.test.ts
tests/transferChatStart.test.ts

Jira: https://bugs.benetech.org/browse/CHI-141
This PR is related to https://github.com/tech-matters/flex-plugins/pull/101
Added two new functions: 
- `transferChatStart`: from the task being transferred, creates a new task with the same channel as the former one, and closes the original if the transfer mode is `cold`
- `transferChatResolve`: used only for `warm` transfers, closes one task, leaves the other one open and kicks the counselor that is not required anymore

Add transfer task functionality

---

functions/transferChatStart.ts
tests/transferChatStart.test.ts

Jira: https://bugs.benetech.org/browse/CHI-156
This PR is related to https://github.com/tech-matters/flex-plugins/pull/116
- Added a condition that sends HTTP error status 403 if a counselor attempts to transfer a chat task to an offline worker (`transferChatStarted` function)

Added safeguard against transfers to offline workers

---

functions/transferChatStart.ts
tests/transferChatStart.test.ts

Mimicking behavior of call transfers, when a chat transfer is attempted against a target worker who reached it's capacity limit (for the task channel of the task), the `transferChatStart` return error status 403, preventing the transfer.

Capacity limit reached prevents chat transfers

---

functions/autopilotRedirect.protected.ts
tests/autopilotRedirect.test.ts

Jira: https://bugs.benetech.org/browse/CHI-249
This PR is related to https://github.com/tech-matters/webchat/pull/9
Adds a new attribute (`lockInput`) to the user resource. That attribute is used in webchat to hide the input (maybe the naming is wrong). The webchat is in charge of changing the value of `lockInput` once a counselor joins, using channel events.
Useful docs:
https://www.twilio.com/docs/chat/rest/user-resourcehttps://media.twiliocdn.com/sdk/js/chat/releases/3.2.3/docs/User.html#updateAttributes__anchor

Added a function that pre-process chat tasks

---

functions/adjustChatCapacity.ts
functions/transferChatStart.ts
package-lock.json
package.json
tests/adjustChatCapacity.test.ts
tests/transferChatStart.test.ts

Jira: https://bugs.benetech.org/browse/CHI-256
This PR is related to: https://github.com/tech-matters/flex-plugins/pull/219
- Moved chat channel finding logic to the `adjustChatCapacity` function.
- Added integration for manual pull with transfers: if a counselor has availavable `worker.attributes.maxMessageCapacity`, the chat channel capacity is increased from within `transferChatStart`.

Continue to support transfers with manual pull

---

functions/sendSystemMessage.ts
tests/sendSystemMessage.test.ts

Jira: https://bugs.benetech.org/browse/CHI-314
This PR is related to
- https://github.com/tech-matters/webchat/pull/15
- https://github.com/tech-matters/flex-plugins/pull/349
This PR adds `sendSystemMessage` function, which takes in `taskSid`, `message` and (optionally) `from` parameters, and send a `message` to the channel bounded to the given `taskSid` in behalf of `from`. Default from is "system".

Make the "Counselor has left the chat" message consistent across all text-based channels

---

functions/assignOfflineContact.ts
tests/assignOfflineContact.test.ts

Jira: https://bugs.benetech.org/browse/CHI-500
This PR is related to https://github.com/tech-matters/flex-plugins/pull/361
This PR creates a new task in behalf of a target worker (counselor), in order to be consistent between HRM and Insights reports. 
- If the worker is offline, it's attributes are changed to apply a new routing rule that will prevent other tasks to be reserved (refer to Admin workflow in Development environment to see the complete assignment expression):
`OR (worker.waitingOfflineContact == true AND worker.acceptOnlyTask == task.sid)`
- Even if the counselor is currently active and reached the assigned tasks limit, we have no need to increase channel capacity as we are using "default" channel for this kind of tasks.
Resolved questions:
- Q: Should a counselor be able to …

Add assignOfflineContact function

---

functions/assignOfflineContact.ts
tests/assignOfflineContact.test.ts

Note: reordered some code. Maybe is easier to read the entire file (starting in the handler implementation, at bottom of the file) rather than the diff in GH.
This PR adds more handling to stuck statuses for the tasks being created:
- No task is created (and returns error status code) if worker is already waiting for an offline contact (prevent simultaneous offline contacts. This can be removed if not desired tho).
- If the task is created but the reservation is not, or the reservation is created but not accepted, or is accepted but not completed, we clean out the newly created task and send the attributes to the issuer (debug).
- If the worker was set to available for this process only, rejects all possible pending reservations before going back to offline mode.
WIP: 
- CI (should I …

Better handling in assignOfflineContact for stuck tasks

---

.github/workflows/aselo_development.yml
assets/operatingInfo/aselo-dev.json

This PR adds a json file with operating info for two channels: `webchat` is always open and `facebook` is always closed. The purpose of this is to allow the team to test the behavior of the function in our environment.

[Development only] Added operating info json and envar

---

.github/workflows/aselo_development.yml
assets/operatingInfo/aselo-dev.json

This PR is a reopen of https://github.com/tech-matters/serverless/pull/40 (reverted due to an error in .yaml file).
This PR adds a json file with operating info for two channels: `webchat` is always open and `facebook` is always closed. The purpose of this is to allow the team to test the behavior of the function in our environment.

[Development only][Reopen] Added operating info json and envar

---

.github/workflows/aselo_development.yml

This PR fixes the GH action file for deploying to development. The variable was being loaded in the scope of the action but never pasted into the created `.env` file, thus it was not included in the serverless service.

Fix .yaml file not including env var 

---

.github/workflows/aselo_beta.yml
.github/workflows/south_africa_production.yml
.github/workflows/south_africa_staging.yml
.github/workflows/test_staging.yml
.github/workflows/zambia_production.yml
.github/workflows/zambia_staging.yml

This PR updates GH actions to include the corresponding key of each environment for operating hours file. Note that there is no ZM file, so calling the function without bundling the file first will result in an error.
Corresponding parameters already filled in AWS Parameter Store.

Deploy actions updated with operating info keys

---

functions/adjustChatCapacity.ts
functions/assignOfflineContact.ts
functions/autopilotRedirect.protected.ts
functions/createContactlessTask.ts
functions/getMessages.ts
functions/getTranslation.ts
functions/healthCheck.ts
functions/issueSyncToken.ts
functions/listWorkerQueues.ts
functions/operatingHours.protected.ts
functions/populateCounselors.ts
functions/sendSystemMessage.ts
functions/transferChatResolve.ts
functions/transferChatStart.ts

This PR adds a `console.error` statement on catch block for every function so we can gather more context and useful information whenever an error occurs, in contrast to the current behavior that's not very helpful.
The new statement will output something like

Added console.error on every catch block

---

functions/voiceWebhook.protected.ts
tests/voiceWebhook.test.ts

Every time a task is created, before going directly to Flex, it nows goes through `voiceWebhook` serverless function. If it's not a voice task, nothing is changed. If it's voice, this function will update the task `from` attribute value, making it unique. This is done by appending the `taskSid` onto the `from` attribute value.
**Deployment Plan**
1. Check that Insights behaves as expected;
2. Deploy to all other environments;
3. Setup VoiceWebhook for each account
**How Setup VoiceWebhook for each account?**
1. Deploy `serverless`
2. Copy function URL
3. Open TaskRouter Settings
4. Set Event Callback URL to be the function URL, and mark only **Task Created** Event under **Specific Events**

Change from attribute when creating a new voice task

---

.github/workflows/aselo_development-pre-DRY.yml

This PR includes an extra step to the deployment script in an attempt to support multiple Twitter accounts for a single Twilio account.

Testing approach to support multiple Twitter accounts

---

functions/webhooks/twitter/FlexChannelUpdate.protected.ts

This PR fixes an error @Humairaa127 spotted in Zambia. Once a Twitter task is completed, the FlexChannelUpdate webhook might be called several times, but we wan't to cleanup the user-channel map (Sync Document) only once (to avoid generating error logs that are caused because of trying to "delete something that was already deleted").

FlexChannelUpdate false-positive error fix

---

functions/addCustomerExternalId.protected.ts
functions/assignOfflineContact.ts
tests/addCustomerExternalId.test.ts
tests/assignOfflineContact.test.ts

Jira: https://bugs.benetech.org/browse/CHI-742
This task adds external id into task attributes-> customer object when a new task is created. I've confirmed that the attribute is properly set as soon as the task start existing in Taskrouter, however I have not tested if this fixes the reported Insights bug. The function is deployed in Aselo dev and already linkend so we can test the behavior even before merging the PR (I just don't know how @dee-luo).
To make this work, after the function is deployed in the proper environment, we also need to specify the url as the "Taskrouter callback url", in Twilio console under TaskRouter -> Flex Task Assignment -> Settings -> Event Callbacks.
WIP:
- Unit tests.

Added addCustomerExternalId

---

.github/actions/deploy-beta/action.yml
.github/actions/healthCheck/action.yml
.github/actions/healthCheck/dist/licenses.txt
.github/actions/healthCheck/index.js
.github/actions/healthCheck/package-lock.json
.github/actions/healthCheck/package.json
.github/workflows/aselo_development.yml
.gitignore

This PR is an attempt to split deployment from health check actions, in order to be one step closer to automating the entire setup process for a new helpline.
@nickhurlburt @murilovmachado I'm going to merge this against master to perform tests. In case something goes wrong it's easy to revert this merge commit. Nothing should be affected other than development deployments.

Split deploy from health check actions

---

.github/actions/healthCheck/index.js

This PR intentionally breaks https://github.com/techmatters/serverless/pull/102 to test if the workflow fails if health check fails. It will be reverted the tests.

Intentionally break healthCheck

---

.github/actions/deploy-beta/action.yml
.github/workflows/aselo_development.yml

This PR adds the required env vars needed for case document to the deploy scripts of Aselo Dev.
Notes:
- We already have `secrets.AWS_DEFAULT_REGION` in GH secrets, do you think is really necessary to have `REGION` in Parameter Store?
- Same question goes for the AWS Aselo user's credentials, they could be hosted in GH secrets, but that will continue to split our sources of truth.
- I'm merging this PR to test it, but feel free to leave comments so I can address them.

Added env vars required for case document feature

---

.github/actions/deploy-beta/action.yml

This fixes an issue where `S3_BUCKET` was getting `AWS_REGION` value and vice versa.
Needs to redeploy every helpline that was deployed with this issue. Only development?

Fix Deploy Beta Actions

---

functions/saveContactToSaferNet.ts

PRs: [CHI-847](https://bugs.benetech.org/browse/CHI-847), [CHI-850](https://bugs.benetech.org/browse/CHI-850), [CHI-848](https://bugs.benetech.org/browse/CHI-848)
This PR introduces 2 new env vars (just for SaferNet environments):
- SAFERNET_ENDPOINT
- SAFERNET_TOKEN
Right now I'm setting them directly on Twilio Console. We may think later on how to automate these env vars that are specific to a helpline.

Implement saveContactToSaferNet function

---

.github/actions/custom-actions/action.yml

This PR fixes an existing issue in https://github.com/techmatters/serverless/pull/158, where the `if` condition always evaluates to true and hence all custom actions are run.
See https://github.com/actions/runner/issues/1173#issuecomment-950153393
Code tested in https://github.com/techmatters/serverless/pull/164

Fixed if condition by using format function

---

assets/translations/pt-BR/postSurveyMessages.private.json
functions/postSurveyInit.ts

Jira: https://bugs.benetech.org/browse/CHI-829
This PR is related to https://github.com/techmatters/flex-plugins/pull/557
This PR:
- Adds `pt-BR` file for post survey translations. I think we will eventually add more messages to this, that's why I've created an isolated file, let me know if you prefer to have it merged with the already existing `messages.private.json` one.
- `postSurveyInit` will try to translate the initial message if there's a `taskLanguage` parameter being sent to the request.

Enables post survey initial message to be translated

---

functions/saveContactToSaferNet.ts

Jira ticket: https://bugs.benetech.org/browse/CHI-924
Primary reviewer: @nickhurlburt 
This PR encodes the payload before generating the signature.
This solution was discussed with Caio from SaferNet and it fixes the issue we were getting with accents in the payload.
Note that we're only encoding the payload for creating the signature, not the body of the POST.

Encode payload before signing it

---

functions/assignOfflineContact.ts
tests/assignOfflineContact.test.ts

This PR fixes a potential bug when assigning an offline contact. Previously we looked for an available activity using the `friendlyName`, but now that we have helplines with different languages this might change, so the check is now changed to use the `available` property of the activities.
Primary reviewer: @murilovmachado  
[:negative_squared_cross_mark:  ] Corresponding issue has been opened
[:heavy_check_mark: ] ~New tests added~ Tests matches this change
- Start a local server with `npm run start`
- Expose the local server to the internet (using ngrok that can be done with `ngrok http <port>`, this requires configuring ngrok authtoken, you can obtain that login into https://dashboard.ngrok.com/get-started/setup).
- From Flex, change the Serverless url like …

Change available check in assignOfflineContact

---

.github/workflows/aarambh_production.yml
.github/workflows/aarambh_staging.yml
.github/workflows/aselo_beta.yml
.github/workflows/ethiopia_production.yml
.github/workflows/ethiopia_staging.yml
.github/workflows/malawi_production.yml
.github/workflows/malawi_staging.yml
.github/workflows/south_africa_production.yml
.github/workflows/south_africa_staging.yml
.github/workflows/zambia_production.yml
.github/workflows/zambia_staging.yml

This PR moves the remaining deploy workflows from deploy-beta to use main-action instead. This means that the custom actions process is incorporated, but not running any extra step since there aren't any defined for this workflows (yet).

Replaced deploy-beta to main-action in deploy workflows

---

.github/actions/custom-actions/aselo_development_custom/action.yml
functions/reportToIWF.ts

This PR adds options to provide "live" flag (to report "in production mode") and country id to the reports to IWF. This are optional environment variables in the Serverless instance, and if not provided, we'll just use `'T'` (test) flag and `null` country id.
This env vars should be added in the same custom action as the IWF credentials. Examples can be seen in the Aselo Development custom action (the code is commented out tho).
Instructions for the future selves can be found in https://benetech.app.box.com/notes/911942535061.

Added support for Live_Report and Reporter_Country_ID from env vars

---

assets/formDefinitions/v1/insights/postSurvey.private.json
functions/postSurveyComplete.protected.ts
functions/postSurveyInit.ts

This PR takes a different approach to the post survey:
- Ask the user if can take a survey.
- Add the chatbot to the channel.
- If the user replies yes, the survey takes place.
- If the user replies no, the survey is cancelled (address not saving blank data in HRM).
- If the user does not replies, the task will timeout (adjust the timeout, rn is 30 seconds).

Post survey fixes to avoid double greeting message

---

functions/helpers/customChannels/customChannelToFlex.private.ts
functions/webhooks/twitter/TwitterToFlex.ts

Fixes a bug introduced in https://github.com/techmatters/serverless/pull/206: `instagram` `channelType` was being set for Twitter based tasks.
Also fixes a bad spelling.

Fixed wrong usage of Twitter channel

---

.github/actions/custom-actions/safernet_production_custom/action.yml
.github/actions/custom-actions/safernet_staging_custom/action.yml
functions/saveContactToSaferNet.ts
functions/savePendingContacts.ts

This changes how some functions related to save pending contacts handle authorization.
- `/savePendingContacts`: Previously used `twilio-flex-token-validator.functionValidator` wrapper. Now it looks for a static key.
- `/saveContactToSaferNet`: Previously used `twilio-flex-token-validator.functionValidator` wrapper. Now it uses a combination of `twilio-flex-token-validator.validator` (notice it's not `functionValidator`) or checks for a static key.
With these changes we're able to achieve two things:
1. An external function (AWS lambda) can call `/savePendingContacts` in a secure way using a static key
2. `/saveContactToSaferNet` can be called in a secure way from two different sources: from Aselo app using a Twilio's generated AccessToken; or from an external …

Add static key auth to savePendingContacts

---

functions/saveContactToSaferNet.ts

Small bug correction:
When `/saveContactToSaferNet` is called via lambda, a payload object was being passed instead of a payload string.
This PR fixes `/saveContactToSaferNet` so that it works with either payload type.

Fix saveContactToSaferNet to accept objects or string

---

functions/webhooks/instagram/InstagramToFlex.ts
tests/webhooks/instagram/InstagramToFlex.test.ts

Primary reviewer: @murilovmachado 
This PR handles story tagging in a slightly different way. Before we were always ignoring this events, now we:
- Ignore the event if the user does not have an active covnersation.
- Redirect the media cdn (temporary url) of the story if the user has an active conversation.
Not sure anyone else can test this, as only people with developer role in the IG app can trigger the webhooks. In case you can, this modifications are already deployed to Aselo dev environment, so to test:
- Send an Instagram message to @aselodevelopment ig account.
- Receive the resulting task in Flex.
- [Optional] Exchange some messages.
- Tag in a story the  @aselodevelopment and see the message is properly displayed as above image shows.
- Capture the chat channel sid to use in …

Support Instagram story mentions

---

.github/actions/custom-actions/aselo_development_custom/action.yml
functions/helpers/customChannels/customChannelToFlex.private.ts
functions/webhooks/instagram/InstagramToFlex.ts
tests/webhooks/instagram/InstagramToFlex.test.ts

Primary reviewer: @murilovmachado  
This PR adds support for Instagram message deletion according to the specs in the ticket (link below). The changes are:
- Fixed wrong Parameter Store credential being pulled from in Aselo Development deployment (Facebook page name has changed and credentials regenerated so the old one is not valid anymore).
- Exporting helper function to retrieve the active chat channel for a given user (if it exists). If no channel is returned, then the user does not have an active conversation.
- Added support to include message attributes when sending a message to Flex in a custom channel.
- All Instagram messages now include it's message id (coming from Instagram) in the message attributes, under the propery `messageExternalId`.
- When a message is unset (deleted) …

Support Instagram message deletion webhooks

---

.github/dependabot.yml

Creates a `dependabot.yml` file similar to the one in https://github.com/techmatters/flex-plugins/pull/803 to limit dependabot updates to only security updates that affect `dependencies` (not `devDependencies`) and do not trigger PRs for normal version updates.
Fixes #....

Add dependabot config to reduce PR spam

---

.github/actions/custom-actions/action.yml

I think that `github.workflow == format('Te Guio Colombia II Staging release') `should match an existing working workflow, it wasn't the case before so I updated it.
@acedeywin @stephenhand  also maybe is worth deleting the previous te guio workflow?

Updating to match existing working workflow

---

functions/helpers/chatChannelJanitor.private.ts
functions/helpers/customChannels/customChannelToFlex.private.ts
functions/webhooks/taskrouterCallback.protected.ts

Primary Reviewer: @murilovmachado 
This PR:
- Renames `postSurveyJanitor` to a more general and descriptive one: `chatChannelJanitor`.
- Exposes a small helper to indicate if a channel is `AseloCustomChannel`.
- Adds a new condition on taskrouter callback to perform cleanup on custom channels (prevents stale state).
Notes:
- After this PR is merged, check that the taskrouter webhook url points to `-production` (currently pointing to `-dev`).
- In order for this changes to take effect in existing accounts, we need to enable two more events on taskrouter webhook: `task.deleted` and `task.system-deleted`.
- Above item means that we need to address this in the terraform scripts too (deferring PR on that until this one is approved & merged).
- Decrease the timeout in "send to flex" widget for …

[Bug Fix] Custom channel user-to-channel maps linked to stale channels

---

functions/adjustChatCapacity.ts
functions/assignOfflineContact.ts
functions/autopilotRedirect.protected.ts
functions/createContactlessTask.ts
functions/deleteFile.ts
functions/getFileDownloadUrl.ts
functions/getFileUploadUrl.ts
functions/getMessages.ts
functions/getTranslation.ts
functions/getWorkerAttributes.ts
functions/healthCheck.ts
functions/helpers/addCustomerExternalId.private.ts
functions/issueSyncToken.ts
functions/listWorkerQueues.ts
functions/operatingHours.ts
functions/populateCounselors.ts
functions/postSurveyComplete.protected.ts
functions/postSurveyInit.ts
functions/reportToIWF.ts
functions/sendSystemMessage.ts
functions/transferChatResolve.ts
functions/transferChatStart.ts
functions/webhooks/taskrouterCallback.protected.ts
tests/helpers/addCustomerExternalId.test.ts

Primary reviewer: @nickhurlburt 
This PR attempts to reduce the amount of times we get paged:
- Removes all `console.error`s in `catch` blocks that already raise a Twilio error webhook (as the function will return status code 500).
- Adds error handling on `functions/helpers/addCustomerExternalId.private.ts`, instead than throwing we'll `console.error`, so the Twilio error webhook is called once per occurrence. If this still occurs that can indicate an internal error.
- Moves around check to avoid calling above function for offline contacts, that is where we found conflicts because of the race condition between "removing task that can't be assigned" in `assignOfflineContact` and "adding external id" in the taskrouter callback. Can rollback if we prefer to keep that check inside of it tho. …

Reduce error logs

---

functions/webhooks/taskrouterCallback.protected.ts

I realized I introduced a wrong condition [here](https://github.com/techmatters/serverless/pull/289), because if `taskAttributes.isContactlessTask` is true then that is an offline contact. The correct predicate should negate this condition as in this PR.
This bug is currently deployed to JM prod so this should be prioritized!

[Bug Fix] Fixed isCreateContactTask condition

---

.github/workflows/serverless-pre-release-qa.yml

Set E2E tests run on QA release to use 1 worker

CHI-1441: Set playwright test run to use one worker when cutting a release

---

.github/actions/main-action/action.yml

Primary Reviewer: @GPaoloni 
Set TWILIO_SERVERLESS_API_CONCURRENCY to 1 for production environment deploys & remove dev environment deploys from workflow

Remove dev environment deploys from workflow

---

functions/endChat.ts

Primary Reviewer: @murilovmachado 
This PR has a minor addition to end chat function where it cleans up channel and proxy when a user ends the chat. Also, bot sent message is triggered only on assigned state
Fixes # 1402
- In webchat, while checking in flex, run through the chat and 'end chat' while the task is in 'pending', 'reserved', and 'assigned'

Use chatChannelJanitor to cleanup after end chat in webchat

---

assets/translations/en-GB/messages.private.json
assets/translations/en-US/messages.private.json
assets/translations/pt-BR/messages.private.json
functions/endChat.ts

Primary Reviewer: @GPaoloni or @stephenhand 
- This PR localizes the `EndChatMsg` string - 'User left conversation' with language attribute in webchat's config
- Adds language as a request parameter for EndChat function
- Separation of `getEndChatMessage` logic and error handling
- Adds some assets for some of the languages
Fixes #1402
- Ensuring this branch is deployed, in webchat (local or deployed dev), get to the part where 'End Chat' can be triggered. Check the Bot message
- To test localization, add or change `EndChatMsg` in `assets/translations/{language}/messages`
- Alternatively, in webchat, the language can be hardcoded to a different appropriate one.

Localize EndChatMessage for use in endChat function

---

assets/translations/en-US/postSurveyMessages.private.json
assets/translations/es/postSurveyMessages.private.json
functions/postSurveyComplete.protected.ts
functions/postSurveyInit.ts

Primary reviewer: @murilovmachado 
This PR adds the ability to localize the "post survey complete". The way this is done is, the original (contact) task contains a `language` attribute, it will be passed down to the post survey task when is created (`/postSurveyInit`). This `language` property is retrieved when the survey is completed (`/postSurveyComplete`) and used to retrieve the translation, if it exists.
Note: this is deployed to development to make testing easier,
- Start a new chat contact and accept it from Flex.
- Edit the generated task from Twilio Console, adding the attribute `"language": "es"`.
- Complete the task from Flex.
- Take the post survey from the contact's view and confirm that the last message (when the post survey is done) is translated.

Localizing postSurvey "good bye" message

---

assets/formDefinitions/co-v1/insights/postSurvey.private.json

Reviewer
@Humairaa127 
I'm updating this because I think that the type of answers don't match the current data type for the Twilio attribute.

remapping post survey answers to match datatypes

---

.eslintrc.js
.prettierrc
functions/taskrouterListeners/transfersListener.private.ts
functions/webhooks/taskrouterCallback.protected.ts
package.json
tech-matters-serverless-helpers-lib/.prettierrc
tech-matters-serverless-helpers-lib/package.json
tests/taskrouterListeners/transfersListener.test.ts

* Updates behaviour of chat transfers to treat transfers to queues differently to transfers to counsellors
* Move .prettierrc settings into package.jsons because a bug in webstorm means it doesn't pick them up from .prettierrc
The updated logic means that a 'queue' target transfer will complete the original task as soon as it hits a queue, rather than holding it open until accepted by a worker, which worker transfers do
It also limits the special logic for rejections to worker transfers. Queue transfers just go back on the queue if rejected now
Fixes CHI-1578
See ticket

CHI-1578: Queue Transfer

---

functions/endChat.ts
functions/postSurveyInit.ts
functions/taskrouterListeners/postSurveyListener.private.ts
functions/taskrouterListeners/transfersListener.private.ts
package.json
tests/taskrouterListeners/postSurveyListener.test.ts
tests/webhooks/instagram/InstagramToFlex.test.ts
tsconfig.json

This PR is related to https://github.com/techmatters/flex-plugins/pull/1114
Primary reviewer: @murilovmachado 
Tests are a WIP in this PR, but, it can still be reviewed.
This PR:
- Adds `functions/taskrouterListeners/postSurveyListener.private.ts` with logic to trigger post surveys from the taskrouter callback (instead than from Flex).
- Wraps the chat channel cleanup logic from `functions/endChat.ts` under `!featureFlags.post_survey_serverless_handled`, since this change will allow for "end chat" functionality (webchat) to still interact with the post survey.
- [WIP] New tests added
See https://github.com/techmatters/flex-plugins/pull/1114.

Move task wrapup and post survey trigger logic from Flex to Serverless

---

.github/actions/main-action/action.yml
.github/workflows/deploy-all-staging-accounts.yml
.github/workflows/serverless-pre-release-qa.yml
.github/workflows/serverless-production-release.yml
release-notes/v1.5.0.md

NOTE: review after https://github.com/techmatters/flex-plugins/pull/1147. Any change in that PR will also affect the behavior of this one.
Similarly to https://github.com/techmatters/flex-plugins/pull/1147, this PR adds a new workflow to create Production Releases. It entirely reuses the action introduced in the linked PR (`flex-plugins` repo), so we'll have a central place for this action, same as with most of our shared actions.
This action expects
- To be called with a `tag` ref.
- Takes as an input a `tag-name` for the release.
- Takes as an input a `title` for the release.
If the workflow succeeds, it will create anew tag and a release for it, with the provided `tag-name` and `title` and a body with the text "TO-DO".
This PR shares the [possible …

Create a Prod Release workflow for Serverless

---

functions/selfReportToIWF.ts
tests/selfReportToIWF.test.ts

An issue was occurring where requests were 'hanging' after the first one sometimes for selfReportIWF
This was because the 'FormData' instance used by the function was defined externally. 'FormData' is a stream buffer intended for a single use in a single request. 
It being defined externally resulted in situations where requests were trying to reuse a closed stream and hanging
* Move form data variable inside function scope
* Fix tests
Fixes CHI-1484
Deploy the fix & regression test self reported CSAM

CHI-1484: Fix form data stream state in selfReportIwf

---

functions/webhooks/instagram/InstagramToFlex.ts
tests/webhooks/instagram/InstagramToFlex.test.ts

**Description**
Any message sent to the InstagramToFlex function identified as being a reply to a story will no longer be forwarded on to Flex
[X] Tests Added
[X] Issue Created
Issue:
CHI-1646
Validation Steps:
Not sure, never used Instagram before, I hope @dee-lou will know

CHI-1646: Incoming Instagram Story Replies are ignored

---

.github/actions/custom-actions/aarambh_staging_custom/action.yml
.github/actions/custom-actions/aselo_development_custom/action.yml
functions/selfReportToIWF.ts
tests/selfReportToIWF.test.ts

**Description**
IWF have fixed the cert issue on their test server sothis insecure option is no longer needed
**Issue:**
CHI-1484
**Validation Steps:**
Redeploy and check self reported CSAM feature still works on Aselo Development or RATI

CHI-1484: Remove option to ignore self signed certs when validating TLS certs for IWF self reporting

---

functions/selfReportToIWF.ts
tests/selfReportToIWF.test.ts

Previously, for the self-gen reporting URL flow we were generating: `https://<url>/t?=TOKEN  `
Now it will be: `https://<url>/?t=TOKEN`

Fix IWF Self-Gen URL generator format

---

README.md
package.json

This adds a package script to download local dev .env from ssm
backup your local .env file then run `npm run ssm:local` to pull .env for localstack from SSM. Validate content.

feat: load env from SSM for local dev

---

functions/endChat.ts
tsconfig.json

This PR fixes the bug in which the post-survey task is not ended when calling `endChat`.
The fix:
- Extracted the code that used to end the contact task to a function
- Applied this function to not only the contact task, but to the post-survey task as well
- Handled `channelCleanupRequired` 
Fixes https://tech-matters.atlassian.net/browse/CHI-1870
At webchat, at post-survey stage, the user can hit end chat and the post-survey is ended.

End post survey task

---

.eslintrc.js
functions/webhooks/line/LineToFlex.ts
tests/webhooks/line/LineToFlex.test.ts

Fixes CHI-1972, emojis in text should now not have signature mismatches. The issue was reported to LINE here: https://github.com/line/line-bot-sdk-php/issues/269 . The issue seems to be that LINE is unnecessarily escaping emoji unicode characters for JSON (they don't need to be escaped) and using that 'escaped' text to generate the signature, whereas `JSON.stringify` that we use in our signature generating algorithm does not escape these characters, so we get different signatures generated. 
I'm not sure how complete this fix is, because I don't know exactly which characters are being unnecessarily escaped. This fix was specifically focused on emojis, but other Unicode characters should be tested.
I also beefed up the unit tests so now the signature matching algorithm isn't stubbed out, …

CHI-1972: Fix emojis for line

---

functions/conference/updateParticipant.ts
tests/conference/updateParticipant.test.ts

Adds one more valid update to `conference/updateParticipant`, allowing to set the `muted` attribute of conference participants.
- Call from the conference fronted and confirm it sets the value accordingly.

conference/updateParticipant: Added option to set muted

---

functions/endChat.ts
functions/helpers/addTaskSidToChannelAttributes.private.ts
functions/taskrouterListeners/createContactListener.private.ts
functions/taskrouterListeners/postSurveyListener.private.ts
functions/taskrouterListeners/transfersListener.private.ts
tests/taskrouterListeners/postSurveyListener.test.ts
tests/taskrouterListeners/transfersListener.test.ts

This PR is related to https://github.com/techmatters/webchat/pull/256.
This PR fixes is part of the fix to https://tech-matters.atlassian.net/browse/CHI-1965https://tech-matters.atlassian.net/browse/CHI-1965.
This bug occurs because:
- When a new webchat task is created, we add the `taskSid` to the channel attributes, so we can easily find the corresponding task from by having the channel. This is used in the end chat functionality.
- When a transfer is initiated, a second task with the same channel sid is created. This means that the new "transfer task" (not yet accepted), because of the above behavior, was overriding the original `taskSid` in channel attributes.
In this PR, the task sids of all the tasks related to a channel are instead added to a list in the channel attributes. When …

[Bug fix] Cold transfer stuck in "locked" state when user ends the chat during a transfer

---

functions/conference/updateParticipant.ts
tests/conference/updateParticipant.test.ts

This PR is related to https://github.com/techmatters/flex-plugins/pull/1458.
This PR allows multiple updates on a conference participant in a single API call.
Service tests should be enough :)

Refactored updateParticipant to support multiple updates

---

.github/workflows/serverless-pre-release-qa.yml

This fixes a regression introduced by the new ui e2e tests where the e2e tests now depend on plugin-hrm-form which depends on hrm-form-definitions. I created a reusable action in flex-plugins to handle the install chain for plugin-hrm-form and this uses that before running e2e tests. This also moves to the new internal SSM based configuration in the e2e-tests.
This depends on https://github.com/techmatters/flex-plugins/pull/1474

fix: use new DRY flex-plugin install before e2e tests

---

functions/conference/addParticipant.ts
functions/conference/statusCallback.protected.ts
tests/conference/addParticipant.test.ts

This PR is related to https://github.com/techmatters/flex-plugins/pull/1475.
This PR
- Modifies add participant to include a status callback to track the status of the ongoing external call.
- Adds a conference status callback function that will update a sync document, where the status of the ongoing external call will be tracked to consume from the UI.
See PR linked above.

Added conference/statusCallback to keep track of in progress call

---

functions/conference/getParticipant.ts

This PR is related to https://github.com/techmatters/flex-plugins/pull/1486.
This PR adds `conference/getParticipant` function, used to retrieve information about a single conference participant, like it's label.
](https://tech-matters.atlassian.net/browse/CHI-2024)- [ ] New tests added
See related PR.

Added conference/getParticipant function

---

.github/actions/main-action/action.yml
.github/workflows/custom_helpline.yml
functions/captureChannelWithBot.protected.ts
tests/captureChannelWithBot.test.ts

This PR updates the code to use Lex Bots' updated naming convention

Lex Naming Conventions

---

functions/endChat.ts
functions/taskrouterListeners/postSurveyListener.private.ts
tests/taskrouterListeners/postSurveyListener.test.ts

- Removing support for post survey logic being handled in Flex
Fixes #[1969](https://tech-matters.atlassian.net/browse/CHI-1969)
- Deploying(or ngrok) this branch, and test locally this [PR's](https://github.com/techmatters/flex-plugins/pull/1499) [branch](CHI1969-remove_postsurvey_flexbased) in Flex
- Ensure post survey is triggered when tested

Remove use of post_survey_serverless_handled flag

---

.github/workflows/thailand_staging.yml
functions/taskrouterListeners/janitorListener.private.ts
functions/taskrouterListeners/postSurveyListener.private.ts
functions/taskrouterListeners/transfersListener.private.ts
functions/transfer/helpers.private.ts
tests/taskrouterListeners/janitorListener.test.ts
tests/taskrouterListeners/transfersListener.test.ts

This PR fixes the bug where, after rejecting a line transfer (or any custom channel really), the next message will result in a duplicated contact. 
The were two causes for this bug:
- [Our implementation of the "chat channel janitor"](https://github.com/techmatters/serverless/blob/master/functions/taskrouterListeners/janitorListener.private.ts) was triggered when the transferred task was rejected (hence canceled), resulting in the chat channel being deactivated. The next message will result in an entire new Studio Flow execution which will ultimately be a new task in Flex.
- Twilio's "Channel Janitor" is enabled for all custom channels in Thai staging, which will do the same as above but on every task being completed/canceled, as this is the default behavior. 
When a task is transferred: …

[Bug fix] Duplicated Line contact created when transfer rejected

---

assets/formDefinitions/cl-v1/insights/postSurvey.private.json

Fixing CL mapping since post survey will store strings not number values
Fixes #....

fixing mapping cl

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/channelCapture/chatbotCallback.protected.ts
functions/channelCapture/chatbotCallbackCleanup.protected.ts
functions/channelCapture/lexClient.private.ts
tests/channelCapture/chatbotCallback.test.ts

This PR:
- Factors out the logic to cleanup a channel capture, and serves it as a Serverless function to be used from Studio Flow.
- Swallow Concurrent Client Requests error on chatbot callback to avoid unnecessary pages.
- Make sure this code is deployed to Development.
- Start a new chat contact. After the bot sends the first message, spam messages and confirm there's no "your function returned an error code" logs in Twilio error logger.
- Confirm that the conversational flow (pre survey -> counselor -> post survey) works as expected (no breaking changes in the cleanup).

Added chatbotCallbackCleanup

---

functions/helpers/chatChannelJanitor.private.ts
functions/taskrouterListeners/janitorListener.private.ts
functions/taskrouterListeners/postSurveyListener.private.ts
tests/taskrouterListeners/janitorListener.test.ts

This PR is related to https://github.com/techmatters/flex-plugins/pull/1627
This PR adds more conditions under which the chat channel janitor should be executed. In particular, we want it to execute for all chat channels for those accounts where post survey is disabled, upon any taskrouter event that moves a task to a "final state". A temporary flag `backend_handled_chat_janitor` is introduced in order to make the synchronization between above Flex branch and this code compatible without making a hard dependency in the deploys. Once all accounts are updated we can get rid of this flag.
- Make sure the feature flags are set to `enable_post_survey`: `false` and `backend_handled_chat_janitor`: `true`.
- Make `master` Flex is deployed to Aselo Development.
- Make `master` is deployed to Aselo …

Mimic DeactivateConversation Orchestration in taskrouter listeners

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/channelCapture/chatbotCallbackCleanup.protected.ts
functions/channelCapture/lexClient.private.ts
functions/helpers/addCustomerExternalId.private.ts
functions/postSurveyComplete.protected.ts
functions/postSurveyInit.ts
tests/helpers/addCustomerExternalId.test.ts

This PR fixes some issues found in `/channelCapture/chatbotCallbackCleanup` function, caused because of the assumption that the channel is successfully captured when it may not.
The changes included in this PR are:
- `/channelCapture/channelCaptureHandlers` continues to bubble the error (if any) from the Lex response, but only after the channel attributes have been updated, since those attributes are required in the cleanup function.
- Lex client's `deleteSession` function is wrapped in a Result to avoid throwing, as that can cause the cleanup to error when the Lex session does not exists (due to a channel capture error). With this change we prevent the promise to reject. If we ever need to "consume the error", that can be done by just evaluating the returned result, but right now we …

[Bug fix] Make channel capture cleanup function compatible with channel not captured

---

functions/sendStudioMessage.protected.ts

Creates a new Serverless Function: `sendStudioMessage`.
This function is similar to `sendSystemMessage`, but instead of using `Tokenvalidator`, it is a `.protected` function.
This function will be used on StudioFlows.
Fixes https://tech-matters.atlassian.net/browse/CHI-2170

Create sendStudioMessage function

---

functions/taskrouterListeners/README.md

This PR adds documentation regarding how chat transfers are implemented.
The docs contains [mermaid](https://mermaid.js.org/) diagrams. This are supported by github, and you can install an extension to render them in your IDE.
NOTES: I've realized that there are places where we could "derogate" some responsibility that currently holds Flex into our backend service:
- "Original task" attributes updates before the transfer is started, could be handled in the "start chat transfer" endpoint.
- "Taking task control" after a transfer is accepted could be handled in the taskrouter listeners, altho we must.
Both notes impact chat and voice transfers, so I'm holding for having the approval of the team before spending time in doing so.
- [n/a] New tests added

Document chat transfers

---

.github/actions/custom-actions/action.yml
.github/actions/custom-actions/e2e_development_custom/action.yml
.github/workflows/deploy-multiple-accounts.yml

Refactor how to set helpline code
Since we can't provision a lex chatbot with e2e as the helpline code we will have to change the helpline code for the E2E account to "ee" on serverless
This PR content is the feedback implementation from @stephenhand where I added the _HELPLINE_CODE lookup specifically in a custom action for the E2E account.
Fixes #....

Chi 2213 migrate e2e account autopilot lex

---

functions/getProfileFlagsForIdentifier.protected.ts
functions/getProfileFlagsForIdentifier.ts

This PR is related to https://github.com/techmatters/hrm/pull/495.
This PR is part of the PoC for rejecting contacts for profiles that have been marked as "blocked".
This PR adds a new protected function `getProfileFlagsForIdentifier`. 
The function
- Expects the entire `trigger` object (a.k.a. what triggered a Studio Flow execution). Depending on the type of trigger, the function will pull the `identifier` (and transform it as we do when we store them in our DB), and then will retrieve from HRM all the profile flags associated for this identifier.
- Returns the list of the names associated to the given identifier (if there are multiple profiles, will return all the flags associated to all the profiles).
The idea of this function is to be used from Studio Flows, so the flows can then use …

[POC] Blocked profiles: add getProfileFlagsForIdentifier

---

functions/channelCapture/channelCaptureHandlers.private.ts

- This PR looks into handling a situation where the helpline code contains a number. It would match all digits (0-9) and replace them with no space since Lex doesn't accept numbers.
Fixes #....

Bg fix issue with e2e

---

functions/helpers/customChannels/customChannelToFlex.private.ts
functions/webhooks/modica/FlexToModica.protected.ts
functions/webhooks/modica/ModicaToFlex.ts
package-lock.json
package.json

- This PR adds support for Modica-SMS on the serverless level
- ModicaToFlex will forward messages from Modica into Aselo
- This is a public function and will be the webhook URL on Modica's platform
- FlexToModica is a protected function responsible to forward messages from Flex to Modica
This PR can be merged with no harm.
TODO:
- Check if Modica provides a way to verify the payload being sent
- Maybe investigate why we need to sanitize the user number
- currently it drops the '+' symbol and adds some white space
- we have a function to handle this, but I'm not sure why this happens  
- Update GitHub Workflows to add Modica's environment variables
-  This should be a custom-action, because only one (or a few) helpline(s) uses Modica
- Better error handling
- This PR only logs `Could not …

[Modica POC] Modica serverless functions

---

functions/webhooks/modica/FlexToModica.protected.ts

This PR adds better error handling for errors on FlexToModica function.
Fixes CHI-2518
It's a bit hard to mock an error. This is achievable by using Postman.

CHI-2518 Better error handling when sending a message through Modica

---

functions/webhooks/instagram/FlexToInstagram.protected.ts
tests/webhooks/instagram/FlexToInstagram.test.ts

- This PR updates the Instagram webhook from v12.0 to v19.0 of the Graph API. 
- As part of this work, also configured API version settings for all user calls and app role calls to v19.0, as indicated in the Facebook developer app's advanced settings panel.
- [n/a] New tests added
Fixes # https://tech-matters.atlassian.net/browse/CHI-2553
- Ensure Instagram messaging still works after this branch/PR is deployed 
- I deployed[ this work](https://github.com/techmatters/serverless/actions/runs/7788792237) to Aselo Dev and Instagram messages are still supported

Upgrade Graph API to v19 for supporting instagram messages

---

functions/getProfileFlagsForIdentifier.protected.ts

This PR adds the complete list of chat channels to the implementation of `getIdentifier`, in `functions/getProfileFlagsForIdentifier.protected.ts`, following the same pattern as [getNumberFromTask](https://github.com/techmatters/flex-plugins/blob/4c011a18adaac4f2be7ccb46e334f1e31242cdd2/plugin-hrm-form/src/utils/task.ts#L28) from Flex, since that's the identifier that is stored in the database.
NOTE: this PR servers as a quick fix but ~introduces~ doesn't solve some existing tech debt. We should:
- Unify the places where we reference channels across this repo (Twilio serverless functions).
- Try, if possible, to unify the implementation of [getNumberFromTask](https://github.com/techmatters/flex-plugins/blob/4c011a18adaac4f2be7ccb46e334f1e31242cdd2/plugin-hrm-form/src/utils/task.ts#L28), …

fix: Resolve partial implementation of getIdentifier [CHI-2605]

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/getProfileFlagsForIdentifier.protected.ts
functions/reportToIWF.ts
functions/saveContactToSaferNet.ts
functions/selfReportToIWF.ts
functions/webhooks/instagram/FlexToInstagram.protected.ts
functions/webhooks/line/FlexToLine.protected.ts
package-lock.json
tests/reportToIWF.test.ts
tests/selfReportToIWF.test.ts
tests/webhooks/instagram/FlexToInstagram.test.ts
tests/webhooks/line/FlexToLine.test.ts

The update to axios v0.28.0 introduced a breaking change to the root fuction - i.e. calling `axios(...)` rather than `axios.get(...)` or `axios.post(...)`
The return type for this function is now an object that includes the response object as a 'data' property, amongst other things, rather than just returning the response directly
This PR moves all uses of this function to the HTTP method specific functions, which retains the prior behavioutr of returning the response directly
Fixes #....
Fixes build
Passes unit tests

Fix code for breaking changes in axios v0.26.1 -> v0.28.0 update

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/channelCapture/chatbotCallbackCleanup.protected.ts

… if the capture failed (capturedChannelAttributes is missing)
This PR fixes the bug described in the linked Jira ticket below.
The bug occurs because `chatbotCallbackCleanup` function attempts to call `handleChannelRelease` "capture handler", which assumes that it receives a valid `capturedChannelAttributes` with a `controlTaskSid` property.
If the capture entirely fails from the beginning and the channel does not even gets "captured", `capturedChannelAttributes` are mising from channel attributes causing the cleanup to also fail. This leads to "stuck channels" since we couldn't either capture with bot nor release it to send straight to Flex.
The fix for this is to avoid calling `handleChannelRelease` if the `capturedChannelAttributes` object is entirely missing.
@janorivera will …

fix: prevent chatbotCallbackCleanup from calling handleChannelRelease [CHI-2682]

---

.github/workflows/deploy-multiple-accounts.yml

Remove use of deprecated GH secrets for looking up account SID and use the standard SSM parameter instead.
After this I think those secrets can be deleted
- N/A New tests added
- N/A Feature flags / configuration added
None
Deploy helplines using the various single & multiple deploy workflows - none should fail or have errors in the output
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what …

CHI-2755: Remove use of GH secrets for account SID

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/reportToIWF.ts
functions/saveContactToSaferNet.ts
functions/selfReportToIWF.ts
functions/webhooks/instagram/FlexToInstagram.protected.ts
functions/webhooks/line/FlexToLine.protected.ts
tests/reportToIWF.test.ts
tests/selfReportToIWF.test.ts
tests/webhooks/instagram/FlexToInstagram.test.ts
tests/webhooks/line/FlexToLine.test.ts

Calls to axios.post that were introduced to fix breaking changes in the latest Axios API themselves have an issue where Auth headers are being clobbered - so this replaces them with calls to axios.request
None
* Regression test custom channels
* Regression test CSAM reports
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the …

CHI-2758: Fix axios calls

---

functions/getMediaUrl.ts

- New feature: This is the API call implementation for the Twilio conversations media resource API used to get the temporary URL for media displayed on the transcript(Here is [Flex-plugin PR](https://github.com/techmatters/flex-plugins/pull/2377) )
- Next Course of Action: To implement the unit test for the getMediaUrl function.
None
[CHI-2811](https://tech-matters.atlassian.net/browse/CHI-2811)
You are responsible for ensuring the above steps are …

Chi 2811 support media transcripts

---

functions/channelCapture/captureChannelWithBot.protected.ts
functions/pullTask.ts
functions/taskrouterListeners/adjustCapacityListener.private.ts

This is an attempt to fix the manual pulling issue where transfers leave the worker with too high a chat capacity
The theory is that the flex event we rely on is not fired when the task is completed outside of flex, so we are moving he whole function out of flex and into task router events, where events should be consistent and respected
* Adds a listener to reduce chat capacity of the worker once the task is completed (replicating flex functionality)
* Adds a 'pullTask' endpoint. This will increase the chat capacity of the worker, poll the reservations for this worker for 5 seconds to see if a new one is added - if it is a task is considered to have successfully been 'pulled' - returns a 200 and the task SID. If there is no new reservation seen in the timeout period, a 404 is returned …

CHI-2818: Add support for backend pulling

---

functions/adjustChatCapacity.ts
functions/pullTask.ts
functions/taskrouterListeners/transfersListener.private.ts
tests/taskrouterListeners/transfersListener.test.ts

Adds explicit chat capacity reductions for worker with original task after a transfer. THis prevents a race condition where they can be assigned a new task before their chat capacity is decreased due to completing the task
Also adds an 'increaseUntilCapacityAvailable' mode for adjustChatCapactity that will keep increasing chat capacity until capacity becomes available or the max capacity is reached. I was concerened that 'double decreases' could leave a worker with too low a capacity to pull tasks in some scenarios so this works around that
None
See ticket - ensure worker and queue transfer scenarios are working
Also, ensure that if a worker picks up 3 tasks, then transfers 1 away, they can still pull yet another from the queue.
1. Cut a release tag using the GitHub workflow. Wait for it …

CHI-2818 queue transfer capacity workaround

---

functions/adjustChatCapacity.ts
functions/pullTask.ts
functions/taskrouterListeners/adjustCapacityListener.private.ts
functions/taskrouterListeners/transfersListener.private.ts
functions/transferChatStart.ts

Instead of incrementing by 1 and decrementing by 1, when we need extra capacity we increase configured capacity until the API reports we have some capacity available (which will effectively be the current number of tasks the worker has going +1). Then when any task (or reservation?) is accepted, we reset the configured capacity to 1. This means that the worker will be 'over capacity' whenever they have manually pulled tasks or accepted transfers in addition to other tasks. I can't see that being 'over capacity' has any ill effects, and it means that there will never be circumstances where a worker incorrectly gets assigned new tasks because their capacity is higher than it ought to be.
So what will happen is:
1. Before manually pulling / being offered a transfer, the workers capacity …

CHI-2818: Change capacity adjustment approach

---

functions/helpers/customChannels/customChannelToFlex.private.ts
tests/webhooks/instagram/InstagramToFlex.test.ts
tests/webhooks/line/LineToFlex.test.ts

Looking up a channel in a user channel map now rethrows any error thrown by the sync service other than 'document not found'
None
Regression test custom channels, monitor fullstory post deploy for recurrences of the ticket issue
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion …

CHI-2894: Improve user channel map error handling

---

functions/interaction/interactionChannelParticipants.private.ts
functions/interaction/transitionAgentParticipants.ts
functions/taskrouterListeners/transfersListener.private.ts
tech-matters-serverless-helpers-lib/src/tokenValidator.ts
tests/interaction/transitionAgentParticipants.test.ts
tests/taskrouterListeners/transfersListener.test.ts

Currently any agent can transition all the agents in a Flex interaction into wrapup, meaning they can potentially end other agent's ongoing tasks. This only affects conversations so does not affect any production helplines
This change only allows the function to be called by workers with the supervisor or who currently hold a reservation for the task
- [N/A] Feature flags / configuration added
None
Regression test post surveys, regular contact wrapup and chat transfers on conversations
Try to call the transitionAgentParticipant from postman for a task with a token for a worker who is not a supervisor and does not have a reservation for the target task - it should return a 403
1. Cut a release tag using the GitHub workflow. Wait for it to complete and the notification to be posted in the …

Fix security hole in transitionAgentParticipants

---

functions/helpers/customChannels/flexToCustomChannel.private.ts
functions/interaction/transitionAgentParticipants.ts
tests/interaction/transitionAgentParticipants.test.ts
tests/webhooks/modica/FlexToModica.test.ts
tests/webhooks/telegram/FlexToTelegram.test.ts

Rather than using the participantSid attribute, which only gets set after completing a chatbot, so won't be set in helplines that don't use a chatbot
- [N/A] Feature flags / configuration added
None
See ticket

CHI-2930: Look up first participant to decide if a custom channel message should be forwarded to the service user

---

package-lock.json

Bumps the npm_and_yarn group with 5 updates:
| Package | From | To |
| --- | --- | --- |
| [body-parser](https://github.com/expressjs/body-parser) | `1.20.2` | `1.20.3` | | [express](https://github.com/expressjs/express) | `4.19.2` | `4.21.0` | | [send](https://github.com/pillarjs/send) | `0.18.0` | `0.19.0` | | [serve-static](https://github.com/expressjs/serve-static) | `1.15.0` | `1.16.2` | | [path-to-regexp](https://github.com/pillarjs/path-to-regexp) | `0.1.7` | `0.1.10` |
Updates `body-parser` from 1.20.2 to 1.20.3
- [Release notes](https://github.com/expressjs/body-parser/releases)
- [Changelog](https://github.com/expressjs/body-parser/blob/master/HISTORY.md)
- [Commits](https://github.com/expressjs/body-parser/compare/1.20.2...1.20.3)
Updates `express` from 4.19.2 to 4.21.0
- …

build(deps): bump the npm_and_yarn group with 5 updates

---

functions/helpers/sendErrorMessageForUnsupportedMedia.private.ts
functions/webhooks/serviceConversationListener.protected.ts
tests/webhooks/serviceConversationListener.test.ts

The service conversation listener wasn't correctly resolving to success at the end of a successful execution of the handler. This addresses that and should squash the timeout errors
None
Deploy and verify the errors are no longer being seen
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the …

CHI-2966 fix convo listener

---

functions/checkTaskAssignment.ts
functions/closeTaskAssignment.ts
functions/completeTaskAssignment.ts

This PR introduces two new public functions:|
- `checkTaskAssignment.ts` that checks whether a specific call/chat (identified by taskSid) is active.
- `completeTaskAssignment.ts` allows a supervisor to switch the assignment status to complete a task.
None
- Ensure that this branch is deployed along with https://github.com/techmatters/flex-plugins/pull/2543
- Follow the steps in the PR in Flex
You are responsible for ensuring the above steps are …

CHI-2763 Check for an active contact & complete  task

---

.github/actions/custom-actions/youthline_staging_custom/action.yml

NZ STG: Modica Conversations migration

---

functions/transferChatStart.ts
tests/transferChatStart.test.ts

Use the 'Everyone' queue for direct transfers if it is available to the target worker. This will make the behaviour a little more consistent
- N/A New tests added
- N/A Feature flags / configuration added
None
Do a direct chat transfer of a conversation but don't accept it yet. 
Check the task on Twilio Console - it should be in the 'Everyone' queue
Repeat for different channels and helplines, it should always be in the 'Everyone' queue if it is visible to the target worker
3. Only then move the ticket into …

CHI-2961: converation direct transfer queue

---

.github/actions/custom-actions/youthline_staging_custom/action.yml

NZ STG: Adding IG params

---

functions/taskrouterListeners/transfersListener.private.ts
functions/transferChatStart.ts

Fix issue where a task sid was being passed to the call to remove original participants from a conversation during a queue transfer. The function requires a task object
- N./A Feature flags / configuration added
None
See ticket
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it does not, the following confusion …

CHI-2960: Fix call to remove original participant from a conversation during a queue transfer

---

functions/transferChatStart.ts

Because conversations uses an alternative approach for transferring conversations _i think_ (testing to confirm) that spare capacity isn't required to accept a transfer.
Trying to adjust for the incoming convo is having an undesirable effect, because the transferred convo already counts to the workers current chat capacity even though it is not accepted yet. This means that when we do increase capacity to 'current tasks plus one' to make room for the transfer, we are actually making room for another random task
This PR removes that pre-adjustment for conversations chat transfers
- N/A Feature flags / configuration added
None
See ticket
2. Comment …

CHI-3005: Don't increase chat capacity for conversation transfers

---

functions/getProfileFlagsForIdentifier.protected.ts

Update Support for 'facebook' and 'messenger'

---

.github/actions/custom-actions/youthline_production_custom/action.yml

@stephenhand this will be safe to run before applying the migration on the TF side since I've created dummy values for now.

NZ PROD: adding new variables

---

functions/sendMessageAndRunJanitor.protected.ts

This PR adds support for Conversations based channel to `sendMessageAndRunJanitor`.
@janorivera tested this and seems like it solves the bug.

fix: handle conversatiosn in sendMessageAndRunJanitor function [CHI-3075]

---

functions/hrm/populateHrmContactFormFromTask.ts
functions/hrm/prepopulateForm.ts
functions/taskrouterListeners/adjustCapacityListener.private.ts
functions/taskrouterListeners/createContactListener.private.ts
functions/taskrouterListeners/createHrmContactListener.private.ts
functions/taskrouterListeners/postSurveyListener.private.ts
functions/webhooks/taskrouterCallback.protected.ts
package-lock.json
package.json

* Adds an additional handler to create new contacts when a reservation is accepted, except in the case of offline contact tasks, or tasks created to receive chat transfers
* Loads the form definitions and prepopulates the new contact with data from the task
* Adds the contact ID of the new contact to the task attributes, so the client is aware that the contact has been provided
* All behind an `enable_backend_hrm_contact_creation` feature flag.
We are currently only using the static key encryption on the HRM call. We'll probably need something more secure for production
None
Regression test new call & chat contacts, transfers and offline contacts …

CHI-3069: Backend contact create

---

.github/workflows/serverless-pre-release-qa.yml

Ubuntu Runner for Plawright E2E tests in QA release pinned to v22 while https://github.com/microsoft/playwright/issues/30368 is addressed

Pin back to ubuntu 22 for playwright E2E runner

---

.github/actions/custom-actions/aselo_development_custom/action.yml
functions/webhooks/taskrouterCallback.protected.ts

Add feature flag check for delegating taskrouter webhook calls. 
Get delegated URL from service configuration rather than it being separately configured
CHI-2929
Ensure feature flag only delegates when set, and when it is, the calls succeed when a twilio lambda is deployed to the correct region
This can be done monitoring the serverless log output
You are responsible for ensuring the above steps are completed. If you move a …

CHI-3069: Use flex configuration for twilio lambda URL

---

functions/helpers/addCustomerExternalId.private.ts
functions/taskrouterListeners/createContactListener.private.ts
functions/webhooks/taskrouterCallback.protected.ts
tech-matters-serverless-helpers-lib/src/tokenValidator.ts
tests/helpers/addCustomerExternalId.test.ts
tests/taskrouterListeners/createContactListener.test.ts

Bit of a 'shotgun fix' for CHI-3173 since I can't identify a root cause
* Attempt to add the external_id on TASK_UPDATED as well as TASK_CREATED
* Doesn't attempt to if external_id already exists, to prevent infinite task update loops
None
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If …

CHI-3173: Attempt to add external id on task updated if it hasn't already been added on task.created

---

functions/getTask.ts
functions/getTaskAndReservations.ts

This PR adds functionality to retrieve the reservations for a given task SID. This enhances to retrieval of the conversation media in flex. 
None
- Use this function to go through [verification steps here](https://github.com/techmatters/flex-plugins/pull/2753)
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to test, the QA team will assume the latest tag has the changes. If it …

CHI-3190 Support sending reservations along with task for getTaskAndReservations return

---

functions/taskrouterListeners/postSurveyListener.private.ts

This PR is related to https://github.com/techmatters/flex-plugins/pull/2929.
None

chore: bypass post survey handler if enabled in Lambda [CHI-3218]

---

functions/channelCapture/channelCaptureHandlers.private.ts
functions/channelCapture/chatbotCallback.protected.ts
functions/channelCapture/chatbotCallbackCleanup.protected.ts
functions/channelCapture/lexClient.private.ts
functions/taskrouterListeners/postSurveyListener.private.ts

This PR fixes a bug where channel captures fail for Lex v1 after the changes for Lex v2. The reason is that we have inconsistent formatting for Lex v1 bots (some uppercased). The solution to this bug is to store the bot language with the casing provided without any changes, other than the lower case version sanitized one.
None
You are responsible for ensuring the above steps are completed. If you move a ticket into QA without advising what version to …

fix: Handle Lex v1 language formatting [CHI-3329]
